### ISSUE TITLE
java.lang.NoClassDefFoundError on Android without minify or proguard

### ISSUE THREAD

**Issue by itienne** [RenderHeads/UnityPlugin-AVProVideo#1030]
We have been using AVProVideo for a project. Evrything is fine on UWP and iOS, but when building for Android, we are having the error below. Min SDK 28, Target SDK 30, Unity 2020.3.17. No proguard or minify enabled.

/com.project.nameE/Unity: AndroidJavaException: java.lang.NoClassDefFoundError: com.google.android.exoplr2avp.upstream.DefaultBandwidthMeter
    java.lang.NoClassDefFoundError: com.google.android.exoplr2avp.upstream.DefaultBandwidthMeter
        at com.google.android.exoplr2avp.upstream.DefaultBandwidthMeter.getSingletonInstance(Unknown Source:0)
        at com.renderheads.AVPro.Video.Player_ExoPlayer.InitialisePlayer(Player_ExoPlayer.java:52)
        at com.renderheads.AVPro.Video.Player_Base.Initialise(Player_Base.java:57)
        at com.renderheads.AVPro.Video.Manager.CreatePlayer(Manager.java:30)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/ImmutableListMultimap

**Comment by RenderHeadsSte** [comment]
Can you provide a full logcat output?

Have you tried running our sample scene in a new project?

**Comment by AndrewRH** [comment]
https://stackoverflow.com/questions/53391806/failed-resolution-of-lcom-google-common-collect-immutablemap-at-com-my-app-di

**Comment by itienne** [comment]
The issue was coming from a duplicate jar file from another plugin used on the project. Resolving the duplication allowed us to fix the exceptions and we are now ok.
