### ISSUE TITLE
Application crashes when calling GetCurrentTime() from another thread

### ISSUE THREAD

**Issue by ichi-23** [RenderHeads/UnityPlugin-AVProVideo#1224]
**Describe the issue**
* Opening media on Unity main thread and calling `GetCurrentTime` from another thread makes the application crash
  * Other methods can be called without crashing（at least `Play`, `GetDuration`, `IsBuffering`, `IsFinished`, `IsLooping`, `IsPaused`, `IsPlaying`, `IsSeeking`）
* Confirmed crashes on Core Edition 2.5.2 and 2.5.3 when using ExoPlayer API on Android
* Doesn't crash on Ver.1.11.3

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.5f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Core Edition 2.5.2/2.5.3
 - Operating system version: Android based OS
 - Device model: Meta Quest 2(Oculus Quest 2)
 - Video specs (resolution, frame-rate, codec, file size): Sample Big Buck Bunny video included in asset (360p, 30fps, H264, 254KB)

**To Reproduce**
1. Create new scene in Unity Editor
2. Create `Quad` object and attach/setup `MediaPlayer`, `ApplyToMesh` components
3. Create and attach/setup this Monobehaviour script to `Quad`
```c#
using System.Threading.Tasks;
using RenderHeads.Media.AVProVideo;
using UnityEngine;

public class Test : MonoBehaviour
{
    [SerializeField] 
    private MediaPlayer mediaPlayer;

    void Start()
    {
        mediaPlayer.OpenMedia(false);
        Task.Run(RunOnThread);
    }

    private void RunOnThread()
    {
        _ = mediaPlayer.Control.GetCurrentTime();
    }
}
```
4. Build and run app on Android device
5. Application crashes

**Logs**
```
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): error2491/1048 InputDispatcherDisplay #114 has focused window: 'Window{26c8e57 u0 com.DefaultCompany.AVProMinimum_4/com.unity3d.player.UnityPlayerActivity}'
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): error2491/1048 InputDispatcherBut another display has a focused window:
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): warn2491/1048 InputDispatcherFocused display #0 does not have a focused window.
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): warn2491/1048 InputDispatcherAttempted to unregister already unregistered input channel '26c8e57 com.DefaultCompany.AVProMinimum_4/com.unity3d.player.UnityPlayerActivity (server)'
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info2491/1048 WindowManagerWIN DEATH: Window{26c8e57 u0 com.DefaultCompany.AVProMinimum_4/com.unity3d.player.UnityPlayerActivity}
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info2219/1048 ActivityManagerProcess com.DefaultCompany.AVProMinimum_4 (pid 1270) has died: fore TOP
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): error1153/1048 InputDispatcherchannel '26c8e57 com.DefaultCompany.AVProMinimum_4/com.unity3d.player.UnityPlayerActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): warn1153/1048 InputDispatcherchannel '26c8e57 com.DefaultCompany.AVProMinimum_4/com.unity3d.player.UnityPlayerActivity (server)' ~ Consumer closed input channel or an error occurred. events=0xd
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info3876/3876 ZygoteProcess 1270 exited due to signal 9 (Killed)
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1980/1899 crash-reporteruncaught drop box entry crash report written at /data/misc/crashes/com.DefaultCompany.AVProMinimum_4_2022-07-06_12-52-40-196665.exception.meta
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1452/1270 ProcessSending signal. PID: 1270 SIG: 9
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): warn22562/1048 ActivityTaskManagerForce finishing activity com.DefaultCompany.AVProMinimum_4/com.unity3d.player.UnityPlayerActivity
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1459/1048 DropBoxManagerServiceadd tag=data_app_crash isTagEnabled=true flags=0x2
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): error1452/1270 AndroidRuntimeFATAL EXCEPTION: Thread-7
Process: com.DefaultCompany.AVProMinimum_4, PID: 1270
java.lang.IllegalStateException: Player is accessed on the wrong thread.
Current thread: 'Thread-7'
Expected thread: 'UnityMain'
See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
  at com.google.android.exoplr2avp.ExoPlayerImpl.verifyApplicationThread(ExoPlayerImpl.java:2600)
  at com.google.android.exoplr2avp.ExoPlayerImpl.getCurrentTimeline(ExoPlayerImpl.java:1194)
  at com.renderheads.AVPro.Video.Player_ExoPlayer.GetCurrentTimeS(Player_ExoPlayer.java:8)
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info6122/804 ServiceManagementgetService: Trying again for android.hardware.drm@1.0::IDrmFactory/clearkey...
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1303/1270 AVProVideoVideo Loading: jar|zip|obb
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): debug32527/905 xrspdreceive ping: org 0 recv 0 xmt 1626791623094300 (received at 9004109970307), offset divergence -342066
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): debug32527/905 xrspdnew clock offset=1617787513157282 (rtt: 847728, dispersion: 8388607500221478, jitter: 110697)
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): debug32527/905 xrspdreceive pong: org 9001018038954 recv 1626788531620100 xmt 1626791622450600 (received at 9004109717182), offset divergence -323941
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1303/1270 Unity[AVProVideo] Opening jar:file:///data/app/com.DefaultCompany.AVProMinimum_4-g9DW15mxLyKGXYMIA5f9uw==/base.apk!/assets/AVProVideoSamples/BigBuckBunny-360p30-H264.mp4 (offset 0) with API ExoPlayer
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1153/1048 chattyuid=1000(system) InputDispatcher identical 1 line
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1303/1270 Unity[AVProVideo] Opening jar:file:///data/app/com.DefaultCompany.AVProMinimum_4-g9DW15mxLyKGXYMIA5f9uw==/base.apk!/assets/AVProVideoSamples/BigBuckBunny-360p30-H264.mp4 (offset 0) with API ExoPlayer
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1303/1270 Unity[AVProVideo] Initialising AVPro Video v2.5.3 (native plugin v2.5.3f1-core) on Adreno (TM) 650/OpenGL ES 3.2 V@0631.0 (GIT@2a1f322ebf, I741fad557a, 1646299164) (Date:03/03/22) (MT True) on Android
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): warn1858/1830 OsSdkRequested historical tracking state too far in the past; oldest: 9003.722122s, requested: 8998.689506s
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info1153/1048 chattyuid=1000(system) InputDispatcher identical 3 lines
Wed Jul 06 2022 12:52:40 GMT+0900 (日本標準時): info581/4041 VrApiFPS=90/90,Prd=37ms,Tear=0,Early=50,Stale=0,VSnc=0,Lat=-1,Fov=0,CPU4/GPU=4/3,1382/490MHz,OC=FF,TA=0/70/0,SP=N/F/N,Mem=1555MHz,Free=3548MB,PLS=0,Temp=30.2C/0.0C,TW=2.87ms,App=3.60ms,GD=0.00ms,CPU&GPU=8.90ms,LCnt=4,GPU%=0.77,CPU%=0.30(W0.38),DSF=1.00
Wed Jul 06 2022 12:52:39 GMT+0900 (日本標準時): info1303/1270 Unity[AVProVideo] Creating player 0
Wed Jul 06 2022 12:52:39 GMT+0900 (日本標準時): info1303/1270 Unitym_Video UnityEngine.AndroidJavaObject
Wed Jul 06 2022 12:52:39 GMT+0900 (日本標準時): info1303/1270 AVProVideoCREATED new ExoPlayer object
Wed Jul 06 2022 12:52:39 GMT+0900 (日本標準時): info1303/1270 ExoPlayerImplInit e873d05 [ExoPlayerLib/2.18.0] [hollywood, Quest, Oculus, 29]
Wed Jul 06 2022 12:52:39 GMT+0900 (日本標準時): info1303/1270 Unitys_Interface UnityEngine.AndroidJavaObject
Wed Jul 06 2022 12:52:39 GMT+0900 (日本標準時): debug1303/1270 AVProVideoUnityPluginLoad CALLED
Wed Jul 06 2022 12:52:39 GMT+0900 (日本標準時): debug1303/1270 AVProVideonativeInit : g_iCallDetailsReferenceCount = 1
```
**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by Ste-RH** [comment]
GetCurrentTime is currently not thread safe.  You will need to cache it each update from the main thread if you need access to the value.  It is on the roadmap to make such calls threadsafe, but this will just be done via the mentioned solution and there is no timeframe to implement this currently.
