### ISSUE TITLE
[Android] java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1238]
- Unity version:  2020.3.32f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)):  2.5.6
 - Operating system version: 

I was updated AVPro v2.5.6.

need to set up the HLS Decryption?
Currently, not set.

Error:

```
2022-07-22 15:46:28.000 18219-18516/com.skt.treal.jumpvrm I/Unity: [AVProVideo] Initialising AVPro Video v2.5.6 (native plugin v2.5.6f1-core) on Adreno (TM) 730/OpenGL ES 3.2 V@0615.0 (GIT@14346e4fbf, I5a600b858e, 1652378231) (Date:05/12/22) (MT True) on Android
    RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
    RenderHeads.Media.AVProVideo.MediaPlayer:OpenMedia(Boolean)
    ifland.UCF.Media.Service.MediaProvider:EnsureMediaProvider(MediaUser, LandMediaData, Action`1)
    ifland.UCF.Media.Service.MediaService:SyncMediaData(iflandUser, iflandInfo, Boolean, Action`1)
    ifland.UCF.App.ServiceController.<PresentationSetup>d__10:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
    UnityEngine.Events.UnityAction:Invoke()
    System.Action:Invoke()
    System.Action`1:Invoke(T)
    System.Action`1:Invoke(T)
    System.Action`1:Invoke(T)
    ifland.UCF.Telepresence.<>c__DisplayClass64_0:<InitializationLand>g__ResponseMeetupRoomInitialization|0(S2C_ROOM_INITIALIZATION_ACK)
    System.Action`1:Invoke(T)
    ifland.UCF.Telepresence.TNetMessageHandler:Update()
2022-07-22 15:46:28.001 18219-18516/com.skt.treal.jumpvrm I/Unity: [AVProVideo] Opening https://f58054c8a1fe41578a1ca586b0186763.azureedge.net/3fb85cbc-c142-4363-9891-81525a50a198/dda7bb19-18aa-41ec-8650-84e60bfc.ism/manifest(audio-only=false,format=m3u8-aapl-v3).m3u8 (offset 0) with API ExoPlayer
    RenderHeads.Media.AVProVideo.MediaPlayer:InternalOpenMedia()
    ifland.UCF.Media.Service.MediaProvider:EnsureMediaProvider(MediaUser, LandMediaData, Action`1)
    ifland.UCF.Media.Service.MediaService:SyncMediaData(iflandUser, iflandInfo, Boolean, Action`1)
    ifland.UCF.App.ServiceController.<PresentationSetup>d__10:MoveNext()
    UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
    UnityEngine.Events.UnityAction:Invoke()
    System.Action:Invoke()
    System.Action`1:Invoke(T)
    System.Action`1:Invoke(T)
    System.Action`1:Invoke(T)
    ifland.UCF.Telepresence.<>c__DisplayClass64_0:<InitializationLand>g__ResponseMeetupRoomInitialization|0(S2C_ROOM_INITIALIZATION_ACK)
    System.Action`1:Invoke(T)
    ifland.UCF.Telepresence.TNetMessageHandler:Update()
2022-07-22 15:46:28.006 18219-18516/com.skt.treal.jumpvrm E/Unity: AndroidJavaException: java.lang.NullPointerException: Attempt to get length of null array
    java.lang.NullPointerException: Attempt to get length of null array
        at android.util.Base64.encode(Base64.java:496)
        at android.util.Base64.encodeToString(Base64.java:458)
        at com.renderheads.AVPro.Video.Player_Base.SetOverrideDecryptionKey(Player_Base.java:1)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <00000000000000000000000000000000>:0 
      at RenderHeads.Media

```

**Comment by Chris-RH** [comment]
We've not been able to reproduce that here, but we think that we have been able to fix the cause.

Out of interest, could you give us a few more details about your device such as:
SDK version
Android build
Device used
API

**Comment by dw8869** [comment]
@Chris-RH 
Target SDK 32 (Android 12)
Compile SDK : 32.0.0
Build tools: 32.0.0

Device: Galaxy S22+ (SM-S906N)
OS: Android 12

**Comment by dw8869** [comment]
@Chris-RH 
It occurred after updating v2.5.6.
It did not happen in previous versions.

**Comment by Chris-RH** [comment]
Thanks, hopefully it'll be fixed for the next release

**Comment by Chris-RH** [comment]
The latest update has just been released. Please let us know if the problem is fixed :)
