### ISSUE TITLE
Run app in Android Error Class not Found com.renderheads.AVPro.Video.Manager

### ISSUE THREAD

**Issue by cuipeng0216** [RenderHeads/UnityPlugin-AVProVideo#1511]
### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE

**Describe the issue**
Run App in Android,But the Video can not play!Logs Error:
AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager
java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager.
I had added it in Assets\Plugins\Android\proguard-user.txt.IOS platform have not the issue.

**Your Setup (please complete the following information):**
 - Unity version: 2021.3.14
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): the latest version.
 - Operating system version: Android
 - Device model: OnePlus GM1900
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Video not played and get error.

**Logs**
If applicable, add error logs to help explain your problem.

**Screenshots**

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by cuipeng0216** [comment]
I followed your advice.Added  "android.enableDexingArtifactTransform=false" to  the end of file(Assets/Plugins/Android/gradleTemplate.properties).But still getting an error.The following are the details of the error from
Logcat：
023-04-13 14:30:48.848 30477-31328 Unity                   com.raydata.pro.pre                  I  s_Interface UnityEngine.AndroidJavaObject
                                                                                                    RenderHeads.Media.AVProVideo.AndroidMediaPlayer:.ctor(OptionsAndroid)
                                                                                                    RenderHeads.Media.AVProVideo.MediaPlayer:CreateMediaPlayer(OptionsAndroid)
                                                                                                    RenderHeads.Media.AVProVideo.MediaPlayer:CreateMediaPlayer()
                                                                                                    RenderHeads.Media.AVProVideo.MediaPlayer:Initialise()
                                                                                                    RenderHeads.Media.AVProVideo.MediaPlayer:Start()
2023-04-13 14:30:48.850 30477-31328 Unity                   com.raydata.pro.pre                  E  AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplr2avp/Player$Listener;
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplr2avp/Player$Listener;
                                                                                                     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                                                     at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
                                                                                                     at com.unity3d.player.UnityPlayer$g$1.handleMessage(Unknown Source:150)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                     at android.os.Looper.loop(Looper.java:233)
                                                                                                     at com.unity3d.player.UnityPlayer$g.run(Unknown Source:20)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplr2avp.Player$Listener" on path: DexPathList[[zip file "/data/app/~~hRuikfy6VMs3NXqybiAJNQ==/com.raydata.pro.pre-2htKdYnZD6b0gtngxoT85A==/base.apk"],nativeLibraryDirectories=[/data/app/~~hRuikfy6VMs3NXqybiAJNQ==/com.raydata.pro.pre-2htKdYnZD6b0gtngxoT85A==/lib/arm64, /data/app/~~hRuikfy6VMs3NXqybiAJNQ==/com.raydata.pro.pre-2htKdYnZD6b0gtngxoT85A==

**Comment by cuipeng0216** [comment]
I haven`t uesd any of the above you said.At the beginning,LogCat error:" Unity com.raydata.pro.pre E AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplr2avp/Player$Listener".Then,I added (-keep class com.renderheads.AVPro.Video.** { ; }
-keep class com.google.android.exoplr2avp.* { ; }
-keep class com.twobigears.audio360.* { *; })，Then LogCat error:"AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager"

**Comment by cuipeng0216** [comment]
targetSdkVersion       : 33，The same goes for other devices

**Comment by Chris-RH** [comment]
Are you using android studio? have you tried clean and rebuild?

More info on proguard here: 
https://www.guardsquare.com/manual/configuration/usage
https://www.guardsquare.com/manual/troubleshooting/troubleshooting

**Comment by cuipeng0216** [comment]
Yeah,I`m using android studio.I uesd AVProVideo in ILRunTime.It`s a hot update solution like lua.Do you support this hot update architecture？

**Comment by cuipeng0216** [comment]
When I replaced a device to build，A new error message is generated. 
LogCat Error:
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='CreatePlayer' signature='(IZZIIIZIIIIIII)Ljava/lang/Object;' in class Ljava.lang.Object;
                                                                                                    java.lang.NoSuchMethodError: no non-static method with name='CreatePlayer' signature='(IZZIIIZIIIIIII)Ljava/lang/Object;' in class Ljava.lang.Object;
                                                                                                     at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:162)
                                                                                                     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                                                     at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
                                                                                                     at com.unity3d.player.UnityPlayer$g$1.handleMessage(Unknown Source:150)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                     at android.os.Looper.loop(Looper.java:233)
                                                                                                     at com.unity3d.player.UnityPlayer$g.run(Unknown Source:20)
                                                                                                      at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
                                                                                                      at UnityEngine.AndroidJavaObject._Call[ReturnType] (System.String met

**Comment by Chris-RH** [comment]
So you have done a clean and rebuild, and now you get this message? Are you still getting the previous messages?

A few other people have similar error messages:
https://stackoverflow.com/questions/66443253/java-lang-nosuchmethoderror-no-static-method-mymethod
https://stackoverflow.com/questions/68261119/androidjavaexception-java-lang-nosuchmethoderror-no-non-static-method-with-nam
https://stackoverflow.com/questions/63483451/java-lang-nosuchmethoderror-no-non-static-method-with-name-getstatuscode-signa
https://forum.unity.com/threads/java-lang-nosuchmethoderror-no-non-static-method-with-name-getstatuscode-signature-i.1103041/

**Comment by cuipeng0216** [comment]
Yeah,The previous error message no longer exists.Now only this error is displayed.
AndroidJavaException: java.lang.NoSuchMethodError: no non-static method with name='CreatePlayer' signature='(IZZIIIZIIIIIII)Ljava/lang/Object;' in class Ljava.lang.Object;
                                                                                                    java.lang.NoSuchMethodError: no non-static method with name='CreatePlayer' signature='(IZZIIIZIIIIIII)Ljava/lang/Object;' in class Ljava.lang.Object;
                                                                                                     at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:162)
                                                                                                     at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
                                                                                                     at com.unity3d.player.UnityPlayer.access$600(Unknown Source:0)
                                                                                                     at com.unity3d.player.UnityPlayer$g$1.handleMessage(Unknown Source:150)
                                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                     at android.os.Looper.loop(Looper.java:233)
                                                                                                     at com.unity3d.player.UnityPlayer$g.run(Unknown Source:20)
                                                                                                      at UnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) [0x00000] in <00000000000000000000000000000000>:0 
                                                                                                      at UnityEngine.AndroidJNIHelper.GetMethodID (System.IntPtr javaClass,

How can I solve this problem，Please.

**Comment by Chris-RH** [comment]
Did you try anything from the links that I pasted?
