### ISSUE TITLE
Application got hang or Crashed in Android app. 

### ISSUE THREAD

**Issue by Dhass15** [RenderHeads/UnityPlugin-AVProVideo#1601]
Hi,

I Have looking forward for purchasing the videoplayer for our android project in unity.

so i have decide to check with demo pack is that work fine.

there i having a issue after the video loading, that is i have scenario where videos are going to be in the server and directly loading from the server streaming the videos in app.

there i have a single media player and for rendering the video i have used the displayuGUI.
![upload_2023-7-28_0-10-25.png](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/47235956/dabc1cc0-00ae-452d-8882-5a9e27e8f19b)

![upload_2023-7-28_0-11-3.png](https://github.com/RenderHeads/UnityPlugin-AVProVideo/assets/47235956/53966e55-32a6-4539-9bd8-9a1e72774c0c)

I have using 480quality videos and lesser than that

Here how i load the videos from URL ,like

private void VideoLoad(string videoURL)

{

bool isOpening = mediaPlayer.OpenMedia(new MediaPath(videoURL, MediaPathType.AbsolutePathOrURL), autoPlay: true);

// Changing the media hints for content loaded via Path

MediaHints hints = mediaPlayer.FallbackMediaHints;

hints.stereoPacking = StereoPacking.TopBottom;

mediaPlayer.FallbackMediaHints = hints;

}

so the video will, then i will send the videoURL as respective if the video is going to be change.

after doing this after some video played the application got hang or crashed so i have debugged using the android logcat profiler.

Error i am getting is

2023-07-27 23:02:29.018 14969 14992 Warn System.err at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

2023-07-28 00:31:24.355 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)

2023-07-28 00:31:24.355 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)

2023-07-28 00:31:24.355 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

2023-07-28 00:31:24.356 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

2023-07-28 00:31:24.356 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)

2023-07-28 00:31:24.356 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)

2023-07-28 00:31:24.356 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

2023-07-28 00:31:24.360 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

2023-07-28 00:31:24.360 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)

2023-07-28 00:31:24.360 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)

2023-07-28 00:31:24.360 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

2023-07-28 00:31:24.373 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

2023-07-28 00:31:24.373 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)

2023-07-28 00:31:24.373 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)

2023-07-28 00:31:24.373 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

2023-07-28 00:31:24.373 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.nativeRender(Native Method)

2023-07-28 00:31:24.373 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer.access$500(Unknown Source:0)

2023-07-28 00:31:24.374 7146 7184 Warn System.err at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:126)

is anything i am done or need to do some changes

Any thing you could suggest is Helpful for me

Please share your thoughts

Thanks in advance.

**Comment by Chris-RH** [comment]
1. AVPro version?
2. Android device and OS version?
3. Android mediaplayer or Exoplayer?
4. How are you streaming them? 
5. Are you using any sort of encryption?
6. Have you read our documentation on streaming? https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html
7. Have you tried these test stream? https://www.renderheads.com/content/docs/AVProVideo/articles/feature-streaming.html#test-streams
8. Have you tested the media using a new project, our demo mediaplayer scene and your test stream in the mediaplayer component?
9. Can you provide a full, unfiltered logcat please?
10. Can you provide a url that you are trying to test with? unitysupport@renderheads.com if confidential

**Comment by Dhass15** [comment]
Sent mail from kanagamanidhass8@gmail.com
With your required details.

**Comment by Chris-RH** [comment]
I've replied by email 31/7

**Comment by Chris-RH** [comment]
Closed due to lack of replies

**Comment by Dhass15** [comment]
Hi
I worked with the suggestion on the mail and it's working good.
Other than that, we can expect the video player to support the vulkan api? In future
Thanks.

**Comment by Chris-RH** [comment]
Its something that we are working on at the moment. No date yet.
