### ISSUE TITLE
Playback error on Android

### ISSUE THREAD

**Issue by dw8869** [RenderHeads/UnityPlugin-AVProVideo#1635]
Video playing error caused by Playback error on Android

 - Unity version: 2020.3.48f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): Ultra 2.8.4
 - Operating system version: Android 12
 - Device model: Gallaxy S20+

**To Reproduce**
The following error log occurs during playback after OpenMedia and nothing is displayed on the screen. (maybe back texture)

**Logs**
[logs.txt](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/12509206/logs.txt)
```
2023-09-04 12:34:25.204 31776-5619/com.skt.treal.jumpvrm E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplr2avp.ExoPlaybackException: Source error
        at com.google.android.exoplr2avp.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:684)
        at com.google.android.exoplr2avp.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:660)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplr2avp.source.hls.playlist.HlsPlaylistTracker$PlaylistStuckException
        at com.google.android.exoplr2avp.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.processLoadedPlaylist(DefaultHlsPlaylistTracker.java:747)
        at com.google.android.exoplr2avp.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:592)
        at com.google.android.exoplr2avp.source.hls.playlist.DefaultHlsPlaylistTracker$MediaPlaylistBundle.onLoadCompleted(DefaultHlsPlaylistTracker.java:520)
        at com.google.android.exoplr2avp.upstream.Loader$LoadTask.handleMessage(Loader.java:486)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Videos**
https://cph-p2p-msl.akamaized.net/hls/live/2000341/test/master.m3u8

**Comment by Ste-RH** [comment]
I have tried to reproduce this, but the video plays back just fine here (I am using a Xiaomi Mi 10T).

Have you tried rebooting the device?  Do none HLS videos on local storage play?

Are you using the Demo_MediaPlayer scene?

**Comment by dw8869** [comment]
> Have you tried rebooting the device?

Yes, it will be reproduced even after rebooting.

> Do none HLS videos on local storage play?

I dont understand.

> Are you using the Demo_MediaPlayer scene?

I'll try that.




**To Reproduce**
1. mediaPlayer.Pause();
2. mediaPlayer.SeekToLiveTime(0);
3. mediaPlayer.Play();

**Comment by Ste-RH** [comment]
Just an MP4 playing out of StreamingAssets.  One of the videos we supplied with the asset would be best.

**Comment by Chris-RH** [comment]
Hi, 

Have you had any luck using a new project and the Demo_MediaPlayer scene?
Have you tried different streams?

**Comment by Chris-RH** [comment]
So does it work with a VOD?
https://stream.mux.com/4XYzhPXzqArkFI8d1vDsScBLD69Gh1b2.m3u8

**Comment by dw8869** [comment]
@Chris-RH 
VOD does not cause any issues.

**Comment by Chris-RH** [comment]
OK.  I've just had a look and it seems that Exoplayer does not support caching live streams
https://github.com/google/ExoPlayer/issues/10509

**Comment by dw8869** [comment]
Can you block the cache for live streams on AVProVideo?

**Comment by Chris-RH** [comment]
no
