### ISSUE TITLE
Crashes occur on Android, various devices and call stacks

### ISSUE THREAD

**Issue by thevoidky** [RenderHeads/UnityPlugin-AVProVideo#1642]
Hello,
I have got reported some crashes, and I hope your help.
These are parts of them.

**Setup**
 - Unity version: 2021.3.9f1
 - AVPro Video version (number and edition (trial/core/ultra/enterprise)): ultra

**Case 1**
- Operating system version: various
- Device model: HiPadX (Android 11, number only after), RMX3630(13), RMX3241(13), CPH2365(13), M40Air_EEA(11), SM-G986B(13), etc.
- Video specs (resolution, frame-rate, codec, file size): unknown(Open is not logged)

Error Name: java.lang.NullPointerException
Error Message: Attempt to invoke virtual method 'long android.media.MediaTimestamp.getAnchorMediaTimeUs()' on a null object reference
Error Stack:
```
com.renderheads.AVPro.Video.Player_MediaPlayer.UpdateAPITextureTimestampNS(Player_MediaPlayer.java:4)
com.renderheads.AVPro.Video.Player_Base.Render(Player_Base.java:171)
com.renderheads.AVPro.Video.Manager.RenderPlayer(Manager.java:21)
```
logcat(from HiPadX, Android 11):
```
09-11 16:18:46.302 22116 22116 V MediaRouter: Selecting route: RouteInfo{ name=ヘッドホン, description=null, status=null, category=RouteCategory{ name=システム types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
09-11 16:18:46.378 22116 22132 I gralloc4: unregister: id=23f0001e4ad
09-11 16:18:46.382 22116 22132 I gralloc4: unregister: id=23f0001e4ae
09-11 16:18:46.383 22116 22132 I gralloc4: unregister: id=23f0001e4b0
09-11 16:18:46.385 22116 22132 I gralloc4: unregister: id=23f0001e4b1
09-11 16:18:46.386 22116 22132 I gralloc4: unregister: id=23f0001e4b2
09-11 16:18:46.387 22116 22132 I gralloc4: unregister: id=23f0001e4b3
09-11 16:18:46.388 22116 22132 I gralloc4: unregister: id=23f0001e4b4
09-11 16:18:46.390 22116 22132 I gralloc4: unregister: id=23f0001e4b5
09-11 16:18:46.392 22116 22132 I gralloc4: unregister: id=23f0001e4b6
09-11 16:18:46.393 22116 22132 I gralloc4: unregister: id=23f0001e4b7
09-11 16:18:46.395 22116 22132 I gralloc4: unregister: id=23f0001e4b8
09-11 16:18:46.396 22116 22132 I gralloc4: unregister: id=23f0001e4b9
09-11 16:18:46.411 22116 30893 V MediaPlayer: resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
09-11 16:18:46.411 22116 30893 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
09-11 16:18:46.411 22116 30893 V MediaPlayer: resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
09-11 16:18:46.411 22116 30893 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
--------- beginning of crash
09-11 16:18:46.412 22116 31038 E AndroidRuntime: FATAL EXCEPTION: Thread-1605
09-11 16:18:46.412 22116 31038 E AndroidRuntime: Process: ############# package #############, PID: 22116
09-11 16:18:46.412 22116 31038 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.media.MediaTimestamp.getAnchorMediaTimeUs()' on a null object reference
09-11 16:18:46.412 22116 31038 E AndroidRuntime: at com.renderheads.AVPro.Video.Player_MediaPlayer.UpdateAPITextureTimestampNS(Player_MediaPlayer.java:4)
09-11 16:18:46.412 22116 31038 E AndroidRuntime: at com.renderheads.AVPro.Video.Player_Base.Render(Player_Base.java:171)
09-11 16:18:46.412 22116 31038 E AndroidRuntime: at com.renderheads.AVPro.Video.Manager.RenderPlayer(Manager.java:21)
09-11 16:18:46.418 22116 31392 V MediaPlayer: resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
09-11 16:18:46.418 22116 31392 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
```

**Case 2**
- Operating system version: Android 7.1.1
- Device model: CPH1723, CPH1609, OPPO A83T, OPPO A57, etc. (reported only CPH or OPPO)
- Video specs (resolution, frame-rate, codec, file size): unknown(Open is not logged)

Error Name: java.lang.IllegalArgumentException
Error Message: The surface has been released
Error Stack:
```
com.oppo.media.OppoMediaPlayer._setVideoSurface(Native Method)
com.oppo.media.OppoMediaPlayer.setSurface(OppoMediaPlayer.java:714)
android.media.MediaPlayer.handleMediaPlayerError(MediaPlayer.java:884)
android.media.MediaPlayer.-wrap0(MediaPlayer.java)
android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:4438)
android.os.Handler.dispatchMessage(Handler.java:110)
android.os.Looper.loop(Looper.java:232)
com.unity3d.player.UnityPlayer$e.run(Unknown Source)
```
logcat(OPPO A83t, Android 7.1.1):
```
--------- beginning of system
09-03 11:04:51.832 8794 8863 D AudioTrack: audiotrack 0x7b7a9e2500 set Type 3, rate 44100, fmt 1, chn 3, fcnt 0, flags 0104
09-03 11:38:37.158 8794 8863 D AudioTrack: audiotrack 0x7b7a9e2500 stop done
--------- beginning of main
09-03 11:47:17.257 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:18.257 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:19.258 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:20.261 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:21.262 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:22.258 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:23.258 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:24.258 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:25.259 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:26.259 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:27.259 8794 8863 D MediaPlayer: handleMessage msg:(3, 58, 0)
09-03 11:47:27.667 8794 11239 E MediaPlayer: error (100, 2)
09-03 11:47:27.668 8794 11239 E MediaPlayer: error (100, 2)
09-03 11:47:27.684 8794 8863 D MediaPlayer: handleMessage msg:(100, 100, 2)
09-03 11:47:27.684 8794 8863 E MediaPlayer: Error (100,2)
09-03 11:47:27.693 8794 8905 I BufferQueueProducer: [SurfaceTexture-94-8794-1](this:0x7ad52a5000,id:1,api:3,p:576,c:8794) disconnect(P): api 3
09-03 11:47:27.693 8794 8806 I BufferQueueProducer: [SurfaceTexture-84-8794-0](this:0x7ade6fa800,id:0,api:3,p:576,c:8794) disconnect(P): api 3
09-03 11:47:27.703 8794 8911 E MediaPlayer: error (1, -32)
09-03 11:47:27.703 8794 8911 E MediaPlayer: error (1, -38)
09-03 11:47:27.704 8794 8868 E MediaPlayer: error (1, -32)
09-03 11:47:27.709 8794 8866 I BufferQueueProducer: [SurfaceTexture-84-8794-0](this:0x7ade6fa800,id:0,api:3,p:576,c:8794) connect(P): api=3 producer=(576:???) producerControlledByApp=true
09-03 11:47:27.713 8794 8805 I BufferQueueProducer: [SurfaceTexture-94-8794-1](this:0x7ad52a5000,id:1,api:3,p:576,c:8794) connect(P): api=3 producer=(576:???) producerControlledByApp=true
09-03 11:47:27.713 8794 8868 E MediaPlayer: error (1, -32)
09-03 11:47:27.720 8794 8868 E MediaPlayer: error (1, -38)
09-03 11:47:27.725 8794 11239 E MediaPlayer: error (1, -38)
09-03 11:47:27.758 8794 8863 D MediaPlayer: handleMessage msg:(100, 100, 2)
09-03 11:47:27.758 8794 8863 E MediaPlayer: Error (100,2)
09-03 11:47:27.759 8794 8863 D MediaPlayer: handleMessage msg:(100, 1, -32)
09-03 11:47:27.759 8794 8863 E MediaPlayer: Error (1,-32)
09-03 11:47:27.776 8794 8863 I BufferQueueProducer: [SurfaceTexture-84-8794-0](this:0x7ade6fa800,id:0,api:3,p:576,c:8794) disconnect(P): api 3
09-03 11:47:27.812 8794 8863 V OppoMediaPlayer: system load
09-03 11:47:27.923 8794 8863 V OppoMediaPlayer: OppoMediaPlayer
09-03 11:47:27.928 8794 8863 D MediaPlayer: handleMediaPlayerError() mOppoMediaPlayer setDataSource(fd, offset,length) mOffset = 35622424 mLength = 2879640
09-03 11:47:27.929 8794 8863 W HardwarePlatform: mIsQcom 0 mIsMtk 1
09-03 11:47:27.930 8794 8863 W OppoAwesomePlayer: reset in
09-03 11:47:27.930 8794 8863 W OppoAwesomePlayer: reset_l in
09-03 11:47:27.930 8794 8863 W OppoAwesomePlayer: notifyListener_l mSeeking -10579791
09-03 11:47:27.930 8794 8863 W OppoAwesomePlayer: reset_l out
09-03 11:47:27.930 8794 8863 W OppoAwesomePlayer: reset out
09-03 11:47:27.932 8794 8863 W OppoAwesomePlayer: AwesomePlayer
09-03 11:47:27.932 8794 8863 V OppoStagefrightPlayer: StagefrightPlayer
09-03 11:47:27.932 8794 8863 V OppoStagefrightPlayer: initCheck
09-03 11:47:27.932 8794 8863 V OppoStagefrightPlayer: setDataSource(117, 35622424, 2879640)
09-03 11:47:27.932 8794 8863 W OppoAwesomePlayer: setDataSource fd /data/app/############# package #############-2/base.apk
09-03 11:47:27.932 8794 8863 W OppoAwesomePlayer: reset_l in
09-03 11:47:27.932 8794 8863 W OppoAwesomePlayer: notifyListener_l mSeeking 0
09-03 11:47:27.932 8794 8863 W OppoAwesomePlayer: reset_l out
09-03 11:47:27.942 8794 8863 W FfmpegSource: begin SniffFfmpeg
09-03 11:47:27.982 8794 8863 D DrmManagerClient(Native): DrmManagerClient(): mUniqueId=[6221]
09-03 11:47:27.986 8794 8863 D DrmManagerClient(Native): ~DrmManagerClient(): mUniqueId=[6221]
09-03 11:47:27.987 8794 8863 D MediaPlayer: closeFd()
09-03 11:47:27.987 8794 8863 D MediaPlayer: mFd is valid, close it.
09-03 11:47:28.020 12100 12100 D : logcat arg logcat.
09-03 11:47:28.020 12100 12100 D : logcat arg -d.
09-03 11:47:28.020 12100 12100 D : logcat arg -v.
09-03 11:47:28.020 12100 12100 D : logcat arg threadtime.
```

**Case 3**
- Operating system version: various
- Device model: SM-G887N(8.1.0), Pixel 4(7.1.2), M2010J19CG(13), SM-G935T(8.0.0), PBAM00(8.1.0), PEMM00(13), LG-H831(8.0.0), KB2000(13), etc.
- Video specs (resolution, frame-rate, codec, file size): 1024\*1024\*60, AVC1, 2.74MB

Error Name: java.lang.RuntimeException
Error Message: Error during updateTexImage (see logcat for details)
Error Stack:
```
android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:307)
com.renderheads.AVPro.Video.Player_Base.Render(Player_Base.java:114)
com.renderheads.AVPro.Video.Manager.RenderPlayer(Manager.java:21)
```
logcat(PHK110, Android 13):
```
07-08 18:59:03.026 10096 10541 D BufferQueueConsumer: [](id:277000000004,api:0,p:-1,c:10096) connect: controlledByApp=true
07-08 18:59:03.028 10096 10247 I Unity : [AVProVideo] Opening #################################### the file in device ################################# (offset 0) with API MediaPlayer
07-08 18:59:03.028 10096 10247 W Unity : AndroidJNIHelper.GetSignature: using Byte parameters is obsolete, use SByte parameters instead
07-08 18:59:03.028 10096 10247 W Unity : AndroidJNIHelper: converting Byte array is obsolete, use SByte array instead
07-08 18:59:03.034 10048 10048 D shadowsocks: not relay connection
07-08 18:59:03.034 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:03.039 10048 10048 D shadowsocks: not relay connection
07-08 18:59:03.039 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:03.065 10096 10983 D BufferQueueProducer: [SurfaceTexture-175-10096-1](id:277000000004,api:3,p:2155,c:10096) connect: api=3 producerControlledByApp=true
07-08 18:59:03.078 10096 10922 W MediaPlayerNative: info/warning (10110, 0)
07-08 18:59:03.092 10096 10096 D MediaRouter: onRestoreRoute() : route=RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
07-08 18:59:03.092 10096 10096 V MediaRouter: Selecting route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
07-08 18:59:03.093 10096 10247 I Unity : [AVProVideo] Using playback path: MediaPlayer OES (1024x1024@60.00)
07-08 18:59:03.093 10096 10247 I Unity : [AVProVideo] Texture ID: 175
07-08 18:59:03.101 10096 10096 D MediaRouter: onRestoreRoute() : route=RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
07-08 18:59:03.101 10096 10096 V MediaRouter: Selecting route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
07-08 18:59:03.106 10096 10096 D MediaRouter: onRestoreRoute() : route=RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
07-08 18:59:03.106 10096 10096 V MediaRouter: Selecting route: RouteInfo{ name=手机, description=null, status=null, category=RouteCategory{ name=系统 types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
07-08 18:59:03.165 10096 10922 D BufferQueueProducer: [SurfaceTexture-175-10096-1](id:277000000004,api:3,p:2155,c:10096) disconnect: api 3
07-08 18:59:03.167 10096 10114 D BufferQueueProducer: [SurfaceTexture-175-10096-1](id:277000000004,api:3,p:2155,c:10096) connect: api=3 producerControlledByApp=true
07-08 18:59:03.168 10096 10114 D BufferQueueProducer: [SurfaceTexture-175-10096-1](id:277000000004,api:3,p:2155,c:10096) disconnect: api 3
07-08 18:59:03.169 10096 10114 D BufferQueueProducer: [SurfaceTexture-175-10096-1](id:277000000004,api:3,p:2155,c:10096) connect: api=3 producerControlledByApp=true
07-08 18:59:03.202 10096 10114 D qdgralloc: Falling back to default YUV format - no camera/video specific format defined, usage 0x100
07-08 18:59:03.246 10096 10114 W MediaPlayerNative: info/warning (3, 0)
07-08 18:59:03.251 10153 10355 I AlarmManager: setExactAndAllowWhileIdle [name: GCM_HB_ALARM type: 2 triggerAtMillis: 345388741]
07-08 18:59:03.265 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.274 10153 10355 I AlarmManager: setExactAndAllowWhileIdle [name: GCM_HB_ALARM type: 2 triggerAtMillis: 345388765]
07-08 18:59:03.281 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.298 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.314 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.320 10153 10346 I AlarmManager: setExactAndAllowWhileIdle [name: FcmRetry type: 2 triggerAtMillis: 344978759]
07-08 18:59:03.332 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.348 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.381 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.416 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.448 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.466 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.483 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.499 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.516 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.548 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.564 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.580 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.597 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.630 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.663 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.716 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.783 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:03.817 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:04.017 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:04.048 10096 10541 I .gameplugin.P01: createIfNeeded: Recreate new EGLImage since dataspace changed
07-08 18:59:04.173 21733 11006 D ab : 40:[0]
07-08 18:59:04.221 21733 5740 I System.out: [okhttp]:check permission begin!
07-08 18:59:04.222 21733 5740 I System.out: [okhttp]:not MMS!
07-08 18:59:04.222 21733 5740 I System.out: [okhttp]:not Email!
07-08 18:59:04.224 21733 5740 I System.out: [OkHttp] sendRequest>>
07-08 18:59:04.224 21733 5740 I System.out: [OkHttp] sendRequest<<
07-08 18:59:04.366 21733 21733 D ab : 40:[0]
07-08 18:59:04.377 21733 5610 D GameAttributesHelper: isAntiAddictionAccelerate:true
07-08 18:59:04.717 21733 5772 I System.out: [okhttp]:check permission begin!
07-08 18:59:04.717 21733 5772 I System.out: [okhttp]:not MMS!
07-08 18:59:04.717 21733 5772 I System.out: [okhttp]:not Email!
07-08 18:59:04.718 21733 5772 I System.out: [OkHttp] sendRequest>>
07-08 18:59:04.718 21733 5772 I System.out: [OkHttp] sendRequest<<
07-08 18:59:04.722 21733 8062 I System.out: [okhttp]:check permission begin!
07-08 18:59:04.722 21733 8062 I System.out: [okhttp]:not MMS!
07-08 18:59:04.722 21733 8062 I System.out: [okhttp]:not Email!
07-08 18:59:04.727 21733 8062 D TrafficStats: tagSocket(105) with statsTag=0xffffffff, statsUid=-1
07-08 18:59:04.837 21733 8062 I System.out: [OkHttp] sendRequest>>
07-08 18:59:04.837 21733 8062 I System.out: [OkHttp] sendRequest<<
07-08 18:59:04.930 21733 8062 I System.out: [okhttp]:check permission begin!
07-08 18:59:04.930 21733 8062 I System.out: [okhttp]:not MMS!
07-08 18:59:04.930 21733 8062 I System.out: [okhttp]:not Email!
07-08 18:59:04.934 21733 8062 D TrafficStats: tagSocket(156) with statsTag=0xffffffff, statsUid=-1
07-08 18:59:05.016 21733 8062 I System.out: [OkHttp] sendRequest>>
07-08 18:59:05.016 21733 8062 I System.out: [OkHttp] sendRequest<<
07-08 18:59:05.253 21733 6058 I System.out: [okhttp]:check permission begin!
07-08 18:59:05.253 21733 6058 I System.out: [okhttp]:not MMS!
07-08 18:59:05.253 21733 6058 I System.out: [okhttp]:not Email!
07-08 18:59:05.257 21733 6058 D TrafficStats: tagSocket(123) with statsTag=0xffffffff, statsUid=-1
07-08 18:59:05.323 21733 6058 I System.out: [OkHttp] sendRequest>>
07-08 18:59:05.325 21733 6058 I System.out: [OkHttp] sendRequest<<
07-08 18:59:05.405 21733 6058 I TeaLog : s 1 1
07-08 18:59:05.405 21733 6058 I TeaLog : s worked:true 60000
07-08 18:59:06.507 21733 10212 D ab : 40:[0]
07-08 18:59:07.094 10048 10048 D shadowsocks: not relay connection
07-08 18:59:07.095 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:07.098 10048 10048 D shadowsocks: not relay connection
07-08 18:59:07.099 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:07.102 10048 10048 D shadowsocks: not relay connection
07-08 18:59:07.103 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:07.105 10048 10048 D shadowsocks: not relay connection
07-08 18:59:07.106 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:07.107 10048 10048 D shadowsocks: not relay connection
07-08 18:59:07.108 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:07.109 10048 10048 D shadowsocks: not relay connection
07-08 18:59:07.110 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:07.111 10048 10048 D shadowsocks: not relay connection
07-08 18:59:07.112 10048 10048 E shadowsocks: server_recv_cb_recv: Bad file descriptor
07-08 18:59:07.118 10096 10541 W Adreno-GSL: <gsl_ldd_control:553>: ioctl fd 128 code 0xc040094a (IOCTL_KGSL_GPU_COMMAND) failed: errno 22 Invalid argument
07-08 18:59:07.119 10096 10545 W Adreno-GSL: <wait_on_sync_fd:135>: fd 95: error 22 Invalid argument
07-08 18:59:07.120 10096 10541 W Adreno-GSL: <gsl_syncobj_dup_fd:276>: 0x79847d78e0 dup(95) error 9 Bad file descriptor
07-08 18:59:07.120 10096 10541 E .gameplugin.P01: [SurfaceTexture-175-10096-1] syncForReleaseLocked: error dup'ing native fence fd: 0x3000
07-08 18:59:07.121 10096 10541 E AndroidRuntime: FATAL EXCEPTION: Thread-871
07-08 18:59:07.121 10096 10541 E AndroidRuntime: Process: #####################################################################, PID: 10096
07-08 18:59:07.121 10096 10541 E AndroidRuntime: java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
07-08 18:59:07.121 10096 10541 E AndroidRuntime: at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
07-08 18:59:07.121 10096 10541 E AndroidRuntime: at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:307)
07-08 18:59:07.121 10096 10541 E AndroidRuntime: at com.renderheads.AVPro.Video.Player_Base.Render(Player_Base.java:114)
07-08 18:59:07.121 10096 10541 E AndroidRuntime: at com.renderheads.AVPro.Video.Manager.RenderPlayer(Manager.java:21)
07-08 18:59:07.166 21733 10212 D TimeUtils: end status: 0
07-08 18:59:07.167 21733 10212 D TimeUtils: getTimeDelay log: t: 50.1
07-08 18:59:07.167 21733 10212 D TimeUtils: getTTL log: t: 102
07-08 18:59:07.167 21733 10212 D TimeUtils: getPocketLoseRate log: t: 0.0
```

**Case 4**
- Operating system version: various
- Device model: M2012K11C(12), SM-N981N(13), SM-A226B(13), SM-F916N(13), V2124(13), RMX3710(13), 2201116PG(11), Pixel 4(7.1.1), MOTO G9 PLUS(11), 
- Video specs (resolution, frame-rate, codec, file size): unknown(Open is not logged)

Error Name: java.lang.RuntimeException
Error Message: Error during updateTexImage (see logcat for details)
Error Stack:
```
android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:307)
com.renderheads.AVPro.Video.Player_Base.Render(Player_Base.java:114)
com.renderheads.AVPro.Video.Manager.RenderPlayer(Manager.java:21)
```
logcat(M2012K11C, Android 12):
```
--------- beginning of main
09-11 17:48:28.485 12978 13140 V MediaPlayer: resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
09-11 17:48:28.485 12978 13140 V MediaPlayer: resetDrmState: mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
09-11 17:48:28.485 12978 13140 V MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
--------- beginning of crash
09-11 17:48:28.499 12978 14434 E AndroidRuntime: FATAL EXCEPTION: Thread-2914
09-11 17:48:28.499 12978 14434 E AndroidRuntime: Process: ############# package #############, PID: 12978
09-11 17:48:28.499 12978 14434 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.reset()' on a null object reference
09-11 17:48:28.499 12978 14434 E AndroidRuntime: at com.renderheads.AVPro.Video.Player_MediaPlayer$1.run(Player_MediaPlayer.java:1)
09-11 17:48:28.499 12978 14434 E AndroidRuntime: at java.lang.Thread.run(Thread.java:920)
```

**Comment by Chris-RH** [comment]
Which version of AVPro Video are you using? The latest is 2.8.5.
Are you streaming or playing local videos?
What are the full specs of the videos are you using?
Are you using any other audio/video players?
Are you using flutter?
Have you been able to reproduce the errors on your own android device?

**Comment by Chris-RH** [comment]
2.6.2 is over a year old.  I suggest updating to the latest version and see if you are still getting reports of issues.

**Comment by thevoidky** [comment]
Okay, but I'm not sure that it could be updated since the game is on service now.
Anything fix related? This looks like [this](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1642) to me.

**Comment by thevoidky** [comment]
Oh I'm sorry that maybe I've mistaked.
The link is [this](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/1191).

**Comment by Chris-RH** [comment]
Can you update to the latest version and see if it is still an issue please.

**Comment by Chris-RH** [comment]
Please update to the latest version and retest.
