### ISSUE TITLE
AndroidJavaException: android.net.ConnectivityManager$TooManyRequestsException

### ISSUE THREAD

**Issue by MarsKK** [RenderHeads/UnityPlugin-AVProVideo#1910]
Hi Development team

Version:2.6.6

Symptom An exception occurs after the video switchover is frequently performed on the Android platform

2024-06-21 11:24:59.710  3156-3424  Unity                                E  AndroidJavaException: android.net.ConnectivityManager$TooManyRequestsException
                                                                                                    android.net.ConnectivityManager$TooManyRequestsException
                                                                                                    	at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:2881)
                                                                                                    	at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3054)
                                                                                                    	at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:3437)
                                                                                                    	at android.net.ConnectivityManager.registerDefaultNetworkCallback(ConnectivityManager.java:3414)
                                                                                                    	at com.google.android.exoplr2avp.scheduler.RequirementsWatcher.registerNetworkCallbackV24(RequirementsWatcher.java:135)
                                                                                                    	at com.google.android.exoplr2avp.scheduler.RequirementsWatcher.start(RequirementsWatcher.java:90)
                                                                                                    	at com.google.android.exoplr2avp.offline.DownloadManager.<init>(DownloadManager.java:279)
                                                                                                    	at com.google.android.exoplr2avp.offline.DownloadManager.<init>(DownloadManager.java:231)
                                                                                                    	at com.renderheads.AVPro.Video.Player_ExoPlayer.InitialisePlayer(Player_ExoPlayer.java:38)
                                                                                                    	at com.renderhea

**Comment by Chris-RH** [comment]
Please update to the latest version of AVPro Video (version 2.9.3 in your case) and retest.
If there is still an issue, please provide a full logcat in txt form.

**Comment by Chris-RH** [comment]
Please update to the latest version of AVPro Video (version 2.9.3 in your case) and retest.
If there is still an issue, please provide a full logcat in txt form.
