### ISSUE TITLE
Android SetPlaybackRate Error

### ISSUE THREAD

**Issue by redccoma** [RenderHeads/UnityPlugin-AVProVideo#198]
**Describe the bug**

**Your Setup (please complete the following information):**
 - Unity version: 2019.2.6
 - AVPro Video version: 1.10.1
 - Operating system version: Android 9
 - Device model: GalaxyS9
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. APP Start.
2. Excuted Mediaplayer.Control.SetPlaybackRate
 ex ) mediaPlayer.Control.SetPlaybackRate(1f);
3. error.

**Logs**
If applicable, add error logs to help explain your problem.
2019-10-14 15:20:56.032 3542-3626/? E/Unity: AndroidJavaException: java.lang.IllegalArgumentException
    java.lang.IllegalArgumentException
        at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
        at com.google.android.exoplayer2.PlaybackParameters.<init>(PlaybackParameters.java:71)
        at com.google.android.exoplayer2.PlaybackParameters.<init>(PlaybackParameters.java:59)
        at com.RenderHeads.AVProVideo.AVProVideoExoPlayer.SetPlaybackRate(AVProVideoExoPlayer.java:996)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:88)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:214)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
      at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args) [0x00000] in <000000000000000000

**Screenshots**
![image](https://user-images.githubusercontent.com/15643337/66732384-b6bf3480-ee96-11e9-829e-fd00f9853e95.png)
![image](https://user-images.githubusercontent.com/15643337/66732400-c6d71400-ee96-11e9-928f-c2b233349965.png)

**Videos**
If applicable, add a copy of your video or the URL

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
ExoPlayer does not allow rate setting of zero or negative.  What functionality are you expecting to see when setting a rate of zero?  I believe on iOS AVPro Video, a rate of zero will pause playback...though I believe iOS can also handle negative playback rates.

**Comment by RenderHeadsSte** [comment]
We have put safety around the SetPlaybackRate functionality to not allow invalid values.  In addition, setting a rate of zero of less will now pause playback.  This will be available in version 1.10.2 onward.
