### ISSUE TITLE
on anrdoid, crashes immediately on startup, NoClassDefFoundError, ImmutableSet

### ISSUE THREAD

**Issue by HyundongHwang** [RenderHeads/UnityPlugin-AVProVideo#2052]
**Describe the issue**
Hello.
This time, I updated from 3.0.11 to 3.1.1, and the Android build was successful, but after running it, it crashes with NoClassDefFoundError as shown below.
When I test 3.0.11 and 3.1.1 separately, 3.0.11 runs normally.
The android player is minApiLevel=26, targetApiLevel=35.
When updating, I deleted Assets/AVProVideo/* and imported it cleanly because I was worried that legacy files might remain.
I guess the Assets/AVProVideo/Editor/Scripts/PostProcessBuild_Android.cs file has changed a lot, and it seems to be conflicting with the androidx.media3.* libraries and the firebase sdk that I was using before.
I would appreciate it if you could help me even with a small clue.

**Your Setup**
 - Unity version: 2022.3.37f1
 - AVPro Video version : core 3.1.1 
 - Operating system version: android 14
 - Device model: samsung galaxy s22 ultra

**To Reproduce**
1. build for android
2. run
3. crash

<br/>
<br/>
<br/>

**Logs**

```
2024/10/31 01:09:18.901 9263 9263 FATAL EXCEPTION: main
2024/10/31 01:09:18.901 9263 9263 Process: app.streamstudio.stream, PID: 9263
2024/10/31 01:09:18.901 9263 9263 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/collect/ImmutableSet;
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.analytics.connector.internal.zzd.<clinit>(com.google.android.gms:play-services-measurement-api@@22.0.2:77)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.analytics.connector.AnalyticsConnectorImpl.registerAnalyticsConnectorListener(com.google.android.gms:play-services-measurement-api@@22.0.2:3)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.subscribeToAnalyticsEvents(AnalyticsDeferredProxy.java:164)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.lambda$init$2$com-google-firebase-crashlytics-AnalyticsDeferredProxy(AnalyticsDeferredProxy.java:100)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy$$ExternalSyntheticLambda2.handle(Unknown Source:2)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.components.OptionalProvider.whenAvailable(OptionalProvider.java:77)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.init(AnalyticsDeferredProxy.java:82)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.<init>(AnalyticsDeferredProxy.java:63)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.AnalyticsDeferredProxy.<init>(AnalyticsDeferredProxy.java:49)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.FirebaseCrashlytics.init(FirebaseCrashlytics.java:90)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.buildCrashlytics(CrashlyticsRegistrar.java:72)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.CrashlyticsRegistrar.$r8$lambda$Pfd5XmDCFzNyAT9o9H6rDnTBQE4(Unknown Source:0)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.crashlytics.CrashlyticsRegistrar$$ExternalSyntheticLambda0.create(Unknown Source:2)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.tracing.ComponentMonitor.lambda$processRegistrar$0(ComponentMonitor.java:38)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.tracing.ComponentMonitor$$ExternalSyntheticLambda0.create(Unknown Source:4)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.components.ComponentRuntime.lambda$discoverComponents$0$com-google-firebase-components-ComponentRuntime(ComponentRuntime.java:160)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.components.ComponentRuntime$$ExternalSyntheticLambda1.get(Unknown Source:4)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.components.Lazy.get(Lazy.java:53)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.components.ComponentRuntime.doInitializeEagerComponents(ComponentRuntime.java:322)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.components.ComponentRuntime.initializeEagerComponents(ComponentRuntime.java:312)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.FirebaseApp.initializeAllApis(FirebaseApp.java:607)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:300)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:264)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.FirebaseApp.initializeApp(FirebaseApp.java:249)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:69)
2024/10/31 01:09:18.901 9263 9263 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2700)
2024/10/31 01:09:18.901 9263 9263 	at android.content.ContentProvider.attachInfo(ContentProvider.java:2670)
2024/10/31 01:09:18.901 9263 9263 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:61)
2024/10/31 01:09:18.901 9263 9263 	at android.app.ActivityThread.installProvider(ActivityThread.java:8628)
2024/10/31 01:09:18.901 9263 9263 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:8126)
2024/10/31 01:09:18.901 9263 9263 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7812)
2024/10/31 01:09:18.901 9263 9263 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
2024/10/31 01:09:18.901 9263 9263 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2486)
2024/10/31 01:09:18.901 9263 9263 	at android.os.Handler.dispatchMessage(Handler.java:106)
2024/10/31 01:09:18.901 9263 9263 	at android.os.Looper.loopOnce(Looper.java:230)
2024/10/31 01:09:18.901 9263 9263 	at android.os.Looper.loop(Looper.java:319)
2024/10/31 01:09:18.901 9263 9263 	at android.app.ActivityThread.main(ActivityThread.java:9063)
2024/10/31 01:09:18.901 9263 9263 	at java.lang.reflect.Method.invoke(Native Method)
2024/10/31 01:09:18.901 9263 9263 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
2024/10/31 01:09:18.901 9263 9263 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
2024/10/31 01:09:18.902 9263 9263 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.collect.ImmutableSet" on path: DexPathList[[zip file "/data/app/~~aO1wMHa5ZJPuQBlLL8DHqg==/app.streamstudio.stream-UhPmvaptNOKjX-mKjoRy0g==/base.apk"],nativeLibraryDirectories=[/data/app/~~aO1wMHa5ZJPuQBlLL8DHqg==/app.streamstudio.stream-UhPmvaptNOKjX-mKjoRy0g==/lib/arm64, /data/app/~~aO1wMHa5ZJPuQBlLL8DHqg==/app.streamstudio.stream-UhPmvaptNOKjX-mKjoRy0g==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
2024/10/31 01:09:18.902 9263 9263 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
2024/10/31 01:09:18.902 9263 9263 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
2024/10/31 01:09:18.902 9263 9263 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2024/10/31 01:09:18.902 9263 9263 	... 40 more

```

<br/>
<br/>
<br/>

> Assets/Plugins/Android/gradleTemplate.properties

```
org.gradle.jvmargs=-Xmx**JVM_HEAP_SIZE**M
org.gradle.parallel=true
unityStreamingAssets=**STREAMING_ASSETS**
# Android Resolver Properties Start
android.useAndroidX=true
android.enableJetifier=true
# Android Resolver Properties End
**ADDITIONAL_PROPERTIES**
```

<br/>
<br/>
<br/>

> Assets/Plugins/Android/mainTemplate.gradle

```
apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    configurations {
        all*.exclude group: 'com.google.guava', module: 'guava'
        all*.exclude group: 'com.google.guava', module: 'listenablefuture'
    }

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    
// Android Resolver Dependencies Start
    implementation 'com.google.android.gms:play-services-base:18.5.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.firebase:firebase-analytics:22.0.2' // Assets/Firebase/Editor/MessagingDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:12.2.1' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-appcheck:18.0.0' // Assets/Firebase/Editor/AppCheckDependencies.xml:13
    implementation 'com.google.firebase:firebase-appcheck-debug:18.0.0' // Assets/Firebase/Editor/AppCheckDependencies.xml:15
    implementation 'com.google.firebase:firebase-appcheck-playintegrity:18.0.0' // Assets/Firebase/Editor/AppCheckDependencies.xml:17
    implementation 'com.google.firebase:firebase-appcheck-unity:12.2.1' // Assets/Firebase/Editor/AppCheckDependencies.xml:24
    implementation 'com.google.firebase:firebase-app-unity:12.2.1' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-auth:23.0.0' // Assets/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:12.2.1' // Assets/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:21.0.0' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-ndk:19.0.3' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-unity:12.2.1' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-firestore:25.0.0' // Assets/Firebase/Editor/FirestoreDependencies.xml:13
    implementation 'com.google.firebase:firebase-firestore-unity:12.2.1' // Assets/Firebase/Editor/FirestoreDependencies.xml:20
    implementation 'com.google.firebase:firebase-iid:21.1.0' // Assets/Firebase/Editor/MessagingDependencies.xml:17
    implementation 'com.google.firebase:firebase-messaging:24.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:12.2.1' // Assets/Firebase/Editor/MessagingDependencies.xml:24
    implementation 'com.google.flatbuffers:flatbuffers-java:1.12.0' // Assets/Firebase/Editor/MessagingDependencies.xml:19
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    ndkPath "**NDKPATH**"

    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**

```

<br/>
<br/>
<br/>

> Library/Bee/Android/Prj/IL2CPP/Gradle/unityLibrary/build.gradle

```
apply plugin: 'com.android.library'
dependencies {
	configurations {
		all*.exclude group: 'com.google.guava', module: 'guava'
		all*.exclude group: 'com.google.guava', module: 'listenablefuture'
	}
	implementation fileTree(dir: 'libs', include: ['*.jar'])
	// Android Resolver Dependencies Start
	implementation 'com.google.android.gms:play-services-base:18.5.0' // Assets/Firebase/Editor/AppDependencies.xml:17
	implementation 'com.google.firebase:firebase-analytics:22.0.2' // Assets/Firebase/Editor/MessagingDependencies.xml:15
	implementation 'com.google.firebase:firebase-analytics-unity:12.2.1' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
	implementation 'com.google.firebase:firebase-appcheck:18.0.0' // Assets/Firebase/Editor/AppCheckDependencies.xml:13
	implementation 'com.google.firebase:firebase-appcheck-debug:18.0.0' // Assets/Firebase/Editor/AppCheckDependencies.xml:15
	implementation 'com.google.firebase:firebase-appcheck-playintegrity:18.0.0' // Assets/Firebase/Editor/AppCheckDependencies.xml:17
	implementation 'com.google.firebase:firebase-appcheck-unity:12.2.1' // Assets/Firebase/Editor/AppCheckDependencies.xml:24
	implementation 'com.google.firebase:firebase-app-unity:12.2.1' // Assets/Firebase/Editor/AppDependencies.xml:22
	implementation 'com.google.firebase:firebase-auth:23.0.0' // Assets/Firebase/Editor/AuthDependencies.xml:13
	implementation 'com.google.firebase:firebase-auth-unity:12.2.1' // Assets/Firebase/Editor/AuthDependencies.xml:20
	implementation 'com.google.firebase:firebase-common:21.0.0' // Assets/Firebase/Editor/AppDependencies.xml:13
	implementation 'com.google.firebase:firebase-crashlytics-ndk:19.0.3' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:13
	implementation 'com.google.firebase:firebase-crashlytics-unity:12.2.1' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:20
	implementation 'com.google.firebase:firebase-firestore:25.0.0' // Assets/Firebase/Editor/FirestoreDependencies.xml:13
	implementation 'com.google.firebase:firebase-firestore-unity:12.2.1' // Assets/Firebase/Editor/FirestoreDependencies.xml:20
	implementation 'com.google.firebase:firebase-iid:21.1.0' // Assets/Firebase/Editor/MessagingDependencies.xml:17
	implementation 'com.google.firebase:firebase-messaging:24.0.0' // Assets/Firebase/Editor/MessagingDependencies.xml:13
	implementation 'com.google.firebase:firebase-messaging-unity:12.2.1' // Assets/Firebase/Editor/MessagingDependencies.xml:24
	implementation 'com.google.flatbuffers:flatbuffers-java:1.12.0' // Assets/Firebase/Editor/MessagingDependencies.xml:19
	// Android Resolver Dependencies End
	implementation(name: 'zaos', ext:'aar')
	implementation(name: 'NatML', ext:'aar')
	implementation(name: 'NatMLHub', ext:'aar')
	implementation(name: 'UniWebView', ext:'aar')
	implementation(name: 'NatCorder', ext:'aar')
	implementation(name: 'simple-crop-image-lib', ext:'aar')
	implementation(name: 'firebase-messaging-cpp', ext:'aar')
	implementation(name: 'VideoKit', ext:'aar')
	implementation project('FirebaseCrashlytics.androidlib')
	implementation project('FirebaseApp.androidlib')
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21'
	implementation 'androidx.browser:browser:1.2.0'
	implementation 'androidx.media3:media3-common:1.4.1'
	implementation 'androidx.media3:media3-container:1.4.1'
	implementation 'androidx.media3:media3-database:1.4.1'
	implementation 'androidx.media3:media3-datasource:1.4.1'
	implementation 'androidx.media3:media3-datasource-cronet:1.4.1'
	implementation 'androidx.media3:media3-datasource-okhttp:1.4.1'
	implementation 'androidx.media3:media3-datasource-rtmp:1.4.1'
	implementation 'androidx.media3:media3-decoder:1.4.1'
	implementation 'androidx.media3:media3-extractor:1.4.1'
	implementation 'androidx.media3:media3-exoplayer:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-dash:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-hls:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-rtsp:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-smoothstreaming:1.4.1'
	implementation 'androidx.media3:media3-exoplayer-workmanager:1.4.1'
}

dependencies.constraints { implementation( "com.google.guava:guava" ) { attributes { attribute( Attribute.of( "org.gradle.jvm.environment", String ), "standard-jvm" ) } } }

// Android Resolver Exclusions Start
android {
	packagingOptions {
		exclude ('/lib/armeabi/*' + '*')
		exclude ('/lib/mips/*' + '*')
		exclude ('/lib/mips64/*' + '*')
		exclude ('/lib/x86/*' + '*')
		exclude ('/lib/x86_64/*' + '*')
	}
}
// Android Resolver Exclusions End
android {
	ndkPath "/Applications/Unity/Hub/Editor/2022.3.37f1/PlaybackEngines/AndroidPlayer/NDK"
	compileSdkVersion 34
	buildToolsVersion '32.0.0'
	compileOptions {
		sourceCompatibility JavaVersion.VERSION_11
		targetCompatibility JavaVersion.VERSION_11
	}
	defaultConfig {
		minSdkVersion 26
		targetSdkVersion 34
		ndk {
			abiFilters 'armeabi-v7a', 'arm64-v8a'
		}
		versionCode 23
		versionName '1.2.3'
		consumerProguardFiles 'proguard-unity.txt', 'proguard-user.txt'
	}
	lintOptions {
		abortOnError false
	}
	aaptOptions {
		noCompress = ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp'] + unityStreamingAssets.tokenize(', ')
		ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
	}
	packagingOptions {
		doNotStrip '*/armeabi-v7a/*.so'
		doNotStrip '*/arm64-v8a/*.so'
	}
}

```

**Comment by Ste-RH** [comment]
com.google.guava is required by media3, yet you are excluding it

**Comment by Ste-RH** [comment]
The reason we had to change the build process (essentially we removed the media3 files from the AVPro Video Android plugin folder and bring them in as a dependencies now) is because the layers of indirection that Unity on Android brings meant that sub dependencies were not making it into a build.  We found that things were fine when using media3 v1.1.0, but moving to v1.4.0 the media3 team had started to use some external dependencies that needed to be brought in.  We had no way of doing this manually, and so had to change to the gradle dependencies method to include media3.

**Comment by Nezz** [comment]
Removing these will fix the issue:
```
configurations {
	all*.exclude group: 'com.google.guava', module: 'guava'
	all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}
```

In our case we worked around the issues created by previous versions of AVPro including guava as a JAR with these changes:
```
configurations {
	all*.exclude group: 'com.google.guava', module: 'guava'
}
```
and
```
implementation 'com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava'
```

As of 3.1.1 no workarounds are needed 🎉

**Comment by HyundongHwang** [comment]
@Ste-RH @Nezz
Thank you.
It works well.
Thanks to you two, I was able to save hours.

As @Nezz said, there was a previous guava library removal statement, but after removing it, it works well.

REMOVE_THIS

```
configurations {
	all*.exclude group: 'com.google.guava', module: 'guava'
	all*.exclude group: 'com.google.guava', module: 'listenablefuture'
}
```
