### ISSUE TITLE
[Android] GetDecoderPerformance: Function Returns  Zero Values

### ISSUE THREAD

**Issue by Tormund** [RenderHeads/UnityPlugin-AVProVideo#2085]
### Unity version

2022.3.15f

### Unity editor platform

macOS

### AVPro Video edition

Ultra

### AVPro Video version

AVPro Video version 3.1.2-ultra build 2410251444

### Device hardware

Quest 3

### Which Android OS version are you using?

12

### Unity Graphics API

OpenGLES 3

### Video API

media3/ExoPlayer

### Texture format

Y Cb Cr 420_OES

### Audio output

System Direct

### Which output component(s) are you using?

Apply to Mesh

### The issue

Currently, this function always returns zero values. I am calling it just before closing the MediaPlayer. Is this the correct way to retrieve dropped frames information from the player?
Code sample:
```
var activeDecodeThreadCount = 0;
var decodedFrameCount = 0;
var droppedFrameCount = 0;
 _player.Info.GetDecoderPerformance(ref activeDecodeThreadCount, ref decodedFrameCount, ref droppedFrameCount);
 Debug.Log($"activeDecodeThreadCount {activeDecodeThreadCount} decodedFrameCount {decodedFrameCount} droppedFrameCount {droppedFrameCount}");
 
```

### Logcat output

```shell
--------- beginning of main
11-26 17:49:20.709 32491 32517 I Unity   : MemoryManager: Using 'Dynamic Heap' Allocator.
11-26 17:49:20.733 32491 32517 I Unity   : SystemInfo CPU = ARM64 FP ASIMD AES, Cores = 3, Memory = 7758mb
11-26 17:49:20.733 32491 32517 I Unity   : SystemInfo ARM big.LITTLE configuration: 3 big (mask: 0x38), 0 little (mask: 0x0)
11-26 17:49:20.733 32491 32517 I Unity   : XR UsableCoreMask: 0x38
11-26 17:49:20.733 32491 32517 I Unity   : ApplicationInfo com.deovr version 14.3
11-26 17:49:20.733 32491 32517 I Unity   : Built from '2022.3/staging' branch, Version '2022.3.15f1 (b58023a2b463)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a', Stripping 'Enabled'
11-26 17:49:21.209 32491 32517 D Unity   : loading library OVRPlugin
11-26 17:49:21.221 32491 32517 D Unity   :  GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_half_float GL_OES_framebuffer_object GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_AMD_compressed_ATC_texture GL_KHR_texture_compression_astc_sliced_3d GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_hdr GL_OES_texture_compression_astc GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_s3tc_srgb GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_bptc GL_OES_texture_npot GL_EXT_texture_filter_anisotropic GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_OES_texture_3D GL_EXT_color_buffer_float GL_EXT_color_buffer_half_float GL_EXT_float_blend GL_QCOM_alpha_test GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_depth_texture_cube_map GL_EXT_sRGB GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_EXT_texture_type_2_10_10_10_REV GL_EXT_texture_sRGB_decode GL_EXT_texture_compression_astc_decode_mode GL_EXT_
11-26 17:49:21.221 32491 32517 D Unity   : texture_mirror_clamp_to_edge GL_EXT_texture_format_sRGB_override GL_OES_element_index_uint GL_EXT_copy_image GL_EXT_geometry_shader GL_EXT_tessellation_shader GL_OES_texture_stencil8 GL_EXT_shader_io_blocks GL_OES_shader_image_atomic GL_OES_sample_variables GL_EXT_texture_border_clamp GL_EXT_EGL_image_external_wrap_modes GL_EXT_multisampled_render_to_texture GL_EXT_multisampled_render_to_texture2 GL_OES_shader_multisample_interpolation GL_EXT_texture_cube_map_array GL_EXT_draw_buffers_indexed GL_EXT_gpu_shader5 GL_EXT_robustness GL_EXT_texture_buffer GL_EXT_shader_framebuffer_fetch GL_ARM_shader_framebuffer_fetch_depth_stencil GL_OES_texture_storage_multisample_2d_array GL_OES_sample_shading GL_OES_get_program_binary GL_EXT_debug_label GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_QCOM_tiled_rendering GL_ANDROID_extension_pack_es31a GL_EXT_primitive_bounding_box GL_OES_standard_derivatives GL_OES_vertex_array_object GL_EXT_disjoint_timer_query GL_KHR_debug GL_EXT_YUV_target GL_EXT
11-26 17:49:21.221 32491 32517 D Unity   : _sRGB_write_control GL_EXT_texture_norm16 GL_EXT_discard_framebuffer GL_OES_surfaceless_context GL_OVR_multiview GL_OVR_multiview2 GL_EXT_texture_sRGB_R8 GL_KHR_no_error GL_EXT_debug_marker GL_OES_EGL_image_external_essl3 GL_OVR_multiview_multisampled_render_to_texture GL_EXT_buffer_storage GL_EXT_external_buffer GL_EXT_blit_framebuffer_params GL_EXT_clip_cull_distance GL_EXT_protected_textures GL_EXT_shader_non_constant_global_initializers GL_QCOM_texture_foveated GL_QCOM_texture_foveated2 GL_QCOM_texture_foveated_subsampled_layout GL_QCOM_shader_framebuffer_fetch_noncoherent GL_QCOM_shader_framebuffer_fetch_rate GL_EXT_memory_object GL_EXT_memory_object_fd GL_EXT_EGL_image_array GL_NV_shader_noperspective_interpolation GL_KHR_robust_buffer_access_behavior GL_EXT_EGL_image_storage GL_EXT_blend_func_extended GL_EXT_clip_control GL_OES_texture_view GL_EXT_fragment_invocation_density GL_QCOM_motion_estimation GL_QCOM_validate_shader_binary GL_QCOM_YUV_texture_gather GL_QCOM_shading_rate GL_QCOM_frame_extrapola
11-26 17:49:21.221 32491 32517 D Unity   : tion GL_QCOM_texture_lod_bias GL_IMG_texture_filter_cubic GL_QCOM_render_shared_exponent GL_EXT_polygon_offset_clamp GL_EXT_texture_sRGB_RG8 GL_EXT_depth_clamp GL_EXT_fragment_shading_rate GL_EXT_fragment_shading_rate_primitive GL_EXT_fragment_shading_rate_attachment GL_EXT_shader_implicit_conversions GL_EXT_render_snorm GL_QCOM_render_sRGB_R8_RG8
11-26 17:49:21.731 32491 32517 I Unity   : Script error: OnJointBreak2D
11-26 17:49:21.731 32491 32517 I Unity   : This message parameter has to be of type: [UNREGISTERED]
11-26 17:49:21.731 32491 32517 I Unity   : The message will be ignored.
11-26 17:49:22.253 32491 32517 I Unity   : XRGeneral Settings awakening...
11-26 17:49:22.253 32491 32517 I Unity   : UnityEngine.XR.Management.XRGeneralSettings:Awake()
11-26 17:49:22.471 32491 32517 I Unity   : QUIC callbacks initialized
11-26 17:49:22.491 32491 32517 W Unity   : [XR] Depth Submission is only supported on Vulkan with Multiview.
11-26 17:49:22.491 32491 32517 D Unity   : initOculus Java!
11-26 17:49:22.491 32491 32491 D Unity   : Oculus UI thread done.
11-26 17:49:22.539 32491 32548 W Unity   : [XR] Symmetric Projection is only supported on Quest 2 with Vulkan and Multiview.
11-26 17:49:22.539 32491 32517 I Unity   : Bootstrap is configuring
11-26 17:49:22.543 32491 32517 I Unity   : Bootstrap is configured
11-26 17:49:23.553 32491 32517 I Unity   : [3D WebView] System info (used by Vuplex support):
11-26 17:49:23.553 32491 32517 I Unity   : Unity version: 2022.3.15f1
11-26 17:49:23.553 32491 32517 I Unity   : Development build: False
11-26 17:49:23.553 32491 32517 I Unity   : OS version: Android OS 12 / API-32 (SQ3A.220605.009.A1/50352750111100510)
11-26 17:49:23.553 32491 32517 I Unity   : Device model: Oculus Quest
11-26 17:49:23.553 32491 32517 I Unity   : Graphics API: OpenGLES3
11-26 17:49:23.553 32491 32517 I Unity   : Rendering threading mode: MultiThreaded
11-26 17:49:23.553 32491 32517 I Unity   : Render pipeline: default
11-26 17:49:23.553 32491 32517 I Unity   : SRP Batcher: True
11-26 17:49:23.554 32491 32517 I Unity   : GVR SDK for Unity version: 1.200.1
11-26 17:49:23.637 32491 32517 I Unity   : Current VR Platform is MetaQuest3
11-26 17:49:23.637 32491 32517 I Unity   : IsOculus: True
11-26 17:49:23.637 32491 32517 I Unity   : Application version: 14.3
11-26 17:49:23.639 32491 32517 I Unity   : OVRVSyncCount OVRPlugin: 1
11-26 17:49:23.639 32491 32517 I Unity   : Antialiasing: 0
11-26 17:49:23.639 32491 32517 I Unity   : RenderScale: 1.5
11-26 17:49:23.639 32491 32517 I Unity   : VSyncCount: 1
11-26 17:49:23.639 32491 32517 I Unity   : Current system is Android OS 12 / API-32 (SQ3A.220605.009.A1/50352750111100510)
11-26 17:49:23.639 32491 32517 I Unity   : Current videocard is Adreno (TM) 740
11-26 17:49:23.639 32491 32517 I Unity   : Current platform is MetaQuest3
11-26 17:49:23.656 32491 32517 I Unity   : XRApp is configuring
11-26 17:49:23.658 32491 32517 I Unity   : Volumetric configuration finished
11-26 17:49:23.673 32491 32517 I Unity   : XRApp is configured
11-26 17:49:23.696 32491 32517 I Unity   : XRApp is ready
11-26 17:49:23.754 32491 32517 I Unity   : Initializing default player...
11-26 17:49:23.758 32491 32517 I Unity   : Initializing default player...
11-26 17:49:23.769 32491 32517 I Unity   : Initializing default player...
11-26 17:49:23.769 32491 32517 I Unity   : Initializing default player...
11-26 17:49:23.773 32491 32517 I Unity   : Initializing default player...
11-26 17:49:23.774 32491 32517 I Unity   : Initializing default player...
11-26 17:49:23.783 32491 32517 I Unity   : Default keybinds for RiftController successfully loaded.
11-26 17:49:23.783 32491 32517 I Unity   : Default keybinds for QuestHandTrackingController successfully loaded.
11-26 17:49:23.785 32491 32517 I Unity   : Default keybinds for GamepadController successfully loaded.
11-26 17:49:23.901 32491 32517 I Unity   : [Volumetric] Device floor position is (0.00, 0.00, 0.00)
11-26 17:49:23.901 32491 32517 I Unity   : [Volumetric] Camera offset is (0.00, 0.00, 0.00)
11-26 17:49:23.901 32491 32517 I Unity   : [Volumetric] Camera position is (0.00, 0.00, 0.00)
11-26 17:49:23.941 32491 32614 W Unity   : The referenced script on this Behaviour (Game Object 'HandTracking') is missing!
11-26 17:49:23.972 32491 32517 I Unity   : [ProjectionMesh] v1.8.1 awakens
11-26 17:49:24.283 32491 32517 I Unity   : Browser initialized.
11-26 17:49:24.289 32491 32517 W Unity   : Camera "Main Camera" does not use a Tracked Pose Driver (Input System), so its transform will not be updated by an XR device.  In order for this to be updated, please add a Tracked Pose Driver (Input System) with bindings for position and rotation of the center eye.
11-26 17:49:24.289 32491 32517 W Unity   : Unity.XR.CoreUtils.XROrigin:Awake()
11-26 17:49:24.364 32491 32517 I Unity   : Numpad is not supported by this keyboard "Keyboard_PIN"
11-26 17:49:24.364 32491 32517 I Unity   : Numpad is not supported by this keyboard "Keyboard_PIN"
11-26 17:49:24.400 32491 32517 I Unity   : ProjectionMesh shader changed to: Unlit/ProjectionShaderOES
11-26 17:49:24.425 32491 32517 W Unity   : [AVProVideo] No camera set for UpdateMultiPassStereo component. If you are rendering in multi-pass stereo then it is recommended to set this.
11-26 17:49:24.425 32491 32517 W Unity   : UnityEngine.GameObject:AddComponent()
11-26 17:49:24.425 32491 32517 W Unity   : AVProRenderer:.ctor(Boolean, RenderType, GameObject, MeshRenderer)
11-26 17:49:24.553 32491 32517 I Unity   : Unity v2022.3.15f1, Oculus Utilities v1.101.0, OVRPlugin v1.101.0, SDK v1.1.38.
11-26 17:49:24.553 32491 32517 I Unity   : SystemHeadset Meta_Quest_3, API OpenXR
11-26 17:49:24.554 32491 32517 I Unity   : OpenXR instance 0x100000000000004 session 0x20000000000004E
11-26 17:49:24.557 32491 32517 I Unity   : OVRPlugin.Media not initialized
11-26 17:49:24.561 32491 32517 I Unity   : Current display frequency 72, available frequencies [72, 80, 90, 120]
11-26 17:49:24.567 32491 32517 W Unity   : Local Dimming feature is not supported
11-26 17:49:24.567 32491 32517 W Unity   : OVRManager:InitOVRManager()
11-26 17:49:24.603 32491 32517 I Unity   : [OVRManager] OnApplicationPause(false)
11-26 17:49:24.603 32491 32517 I Unity   : Android Platform: Application resume
11-26 17:49:24.606 32491 32517 I Unity   : [OVRManager] OnApplicationFocus(true)
11-26 17:49:24.666 32491 32517 I Unity   : playerID: 0000FE48
11-26 17:49:24.666 32491 32517 I Unity   : flags: 00000002
11-26 17:49:24.666 32491 32517 I Unity   : flags: 0002FE48
11-26 17:49:24.669 32491 32517 I Unity   : [AVProVideo] Initialising AVPro Video v3.1.2 (native plugin v3.1.2-ultra) on Adreno (TM) 740/OpenGL ES 3.2 V@0797.0 (GIT@5c44054b8b, I064dd7d485, 1726116466) (Date:09/12/24) (MT True) on Android
11-26 17:49:24.670 32491 32517 I Unity   : playerID: 0000857C
11-26 17:49:24.670 32491 32517 I Unity   : flags: 00000003
11-26 17:49:24.670 32491 32517 I Unity   : flags: 0003857C
11-26 17:49:24.670 32491 32517 I Unity   : playerID: 00004BF1
11-26 17:49:24.670 32491 32517 I Unity   : flags: 00000002
11-26 17:49:24.670 32491 32517 I Unity   : flags: 00024BF1
11-26 17:49:24.671 32491 32517 I Unity   : playerID: 0000AA7F
11-26 17:49:24.671 32491 32517 I Unity   : flags: 00000002
11-26 17:49:24.671 32491 32517 I Unity   : flags: 0002AA7F
11-26 17:49:24.672 32491 32517 I Unity   : playerID: 00008F3B
11-26 17:49:24.672 32491 32517 I Unity   : flags: 00000002
11-26 17:49:24.672 32491 32517 I Unity   : flags: 00028F3B
11-26 17:49:24.673 32491 32517 I Unity   : playerID: 0000DBD3
11-26 17:49:24.673 32491 32517 I Unity   : flags: 00000002
11-26 17:49:24.673 32491 32517 I Unity   : flags: 0002DBD3
11-26 17:49:24.680 32491 32517 E Unity   : AndroidJavaException: java.lang.ClassNotFoundException: org.webrtc.UnityUtility
11-26 17:49:24.680 32491 32517 E Unity   : java.lang.ClassNotFoundException: org.webrtc.UnityUtility
11-26 17:49:24.680 32491 32517 E Unity   : 	at java.lang.Class.classForName(Native Method)
11-26 17:49:24.680 32491 32517 E Unity   : 	at java.lang.Class.forName(Class.java:454)
11-26 17:49:24.680 32491 32517 E Unity   : 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
11-26 17:49:24.680 32491 32517 E Unity   : 	at com.unity3d.player.UnityPlayer.-$$Nest$mnativeRender(Unknown Source:0)
11-26 17:49:24.680 32491 32517 E Unity   : 	at com.unity3d.player.UnityPlayer$F$a.handleMessage(Unknown Source:122)
11-26 17:49:24.680 32491 32517 E Unity   : 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-26 17:49:24.680 32491 32517 E Unity   : 	at android.os.Looper.loopOnce(Looper.java:214)
11-26 17:49:24.680 32491 32517 E Unity   : 	at android.os.Looper.loop(Looper.java:304)
11-26 17:49:24.680 32491 32517 E Unity   : 	at com.unity3d.player.UnityPlayer$F.run(Unknown Source:24)
11-26 17:49:24.680 32491 32517 E Unity   : Caused by: java.lang.ClassNotFoundException: org.webrtc.UnityUtility
11-26 17:49:24.680 32491 32517 E Unity   : 	... 9 more
11-26 17:49:24.680 32491 32517 E Unity   :   at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 
11-26 17:49:24.680 32491 32517 E Unity   :   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 
11-26 17:49:24.680 32491 32517 E Unity   :   at UnityEngine.AndroidJavaClass._AndroidJavaClass (System.String className)
11-26 17:49:24.711 32491 32517 I Unity   : The current MSAA level is 0, but the recommended MSAA level is 4. Switching to the recommended level.
11-26 17:49:24.711 32491 32517 I Unity   : [OVRManager] HMDAcquired event
11-26 17:49:24.711 32491 32517 I Unity   : [OVRManager] HMDMounted event
11-26 17:49:24.712 32491 32517 I Unity   : [OVRManager] VrFocusAcquired event
11-26 17:49:24.712 32491 32517 I Unity   : [OVRManager] InputFocusLost event
11-26 17:49:24.714 32491 32517 I Unity   : Recenter event detected
11-26 17:49:24.737 32491 32517 I Unity   : Quest Colorspace set to Rec_709
11-26 17:49:24.737 32491 32517 I Unity   : AiPtAlphaBlurType Quality
11-26 17:49:24.737 32491 32517 I Unity   : SpatialAudioAllowSwitchToStereo False
11-26 17:49:24.745 32491 32517 I Unity   : Unable to process a controller whose SampleRateHz is 0 now.
11-26 17:49:24.745 32491 32517 I Unity   : Unable to process a controller whose SampleRateHz is 0 now.
11-26 17:49:24.833 32491 32517 I Unity   : Set reload method: ReloadMedia
11-26 17:49:24.918 32491 32517 I Unity   : [OVRManager] InputFocusAcquired event
11-26 17:49:24.918 32491 32517 I Unity   : [OVRManager] TrackingAcquired event
11-26 17:49:24.928 32491 32517 I Unity   : ActionController_ChangeDevice GamepadController Any
11-26 17:49:24.928 32491 32517 I Unity   : ActivateReticle
11-26 17:49:24.967 32491 32517 I Unity   : ActionController_ChangeDevice RiftController Right
11-26 17:49:24.967 32491 32517 I Unity   : ActivateRightController
11-26 17:49:24.988 32491 32517 I Unity   : OVRControllerHelp: Active controller type: TouchPlus for product Meta Quest 3 (headset Meta_Quest_3, hand HandRight)
11-26 17:49:25.638 32491 32517 I Unity   : Redirects loaded: 41
11-26 17:49:28.648 32491 32517 I Unity   : Set reload method: ReloadMedia
11-26 17:49:28.660 32491 32517 I Unity   : GetDefaultCodecType: h265
11-26 17:49:28.660 32491 32517 I Unity   : GetDefaultFPS: 0
11-26 17:49:28.662 32491 32517 I Unity   : Get DefaultRes: -1
11-26 17:49:28.696 32491 32517 I Unity   : GetDefaultCodecType: h265
11-26 17:49:28.696 32491 32517 I Unity   : Get DefaultRes: -1
11-26 17:49:28.697 32491 32517 I Unity   : AVProVideoPlayer UseFastOesPath: True
11-26 17:49:28.697 32491 32517 I Unity   : AVPro Android spatial=False
11-26 17:49:28.703 32491 32517 I Unity   : ScreenType dome
11-26 17:49:28.724 32491 32517 I Unity   : AVProVideoPlayer Event: StartedBuffering
11-26 17:49:29.182 32491 32517 I Unity   : AVProVideoPlayer Event: MetaDataReady
11-26 17:49:29.182 32491 32517 I Unity   : AVProVideoPlayer Event: ReadyToPlay
11-26 17:49:29.182 32491 32517 I Unity   : AVProVideoPlayer Event: FinishedBuffering
11-26 17:49:29.195 32491 32517 I Unity   : AVProVideoPlayer Event: ResolutionChanged
11-26 17:49:29.219 32491 32517 I Unity   : AVProVideoPlayer Event: FirstFrameReady
11-26 17:49:29.227 32491 32517 I Unity   : ScreenType dome
11-26 17:49:29.242 32491 32517 I Unity   : AVProVideoPlayer Event: StartedSeeking
11-26 17:49:29.242 32491 32517 I Unity   : AVProVideoPlayer Event: StartedBuffering
11-26 17:49:29.262 32491 32517 I Unity   : AVProVideoPlayer Event: Started
11-26 17:49:29.587 32491 32517 I Unity   : PlaylistsRow -> MediaIndex: 0 and TotalVideosCount = 6 PageLoaded: 1 PlaylistType: Suggested
11-26 17:49:29.781 32491 32517 I Unity   : AVProVideoPlayer Event: FinishedBuffering
11-26 17:49:29.888 32491 32517 I Unity   : [AVProVideo] XR Device details: UnityEngine.XR.XRSettings.loadedDeviceName = oculus display | supportedDevices = oculus input, oculus display | XR Devices = Meta Quest 3, Oculus Touch Controller - Right | headDevice name = Meta Quest 3, manufacturer = Oculus
11-26 17:49:29.896 32491 32517 I Unity   : AVProVideoPlayer Event: FinishedSeeking
11-26 17:49:30.417 32491 32517 I Unity   : Unable to process a controller whose SampleRateHz is 0 now.
11-26 17:49:30.418 32491 32517 I Unity   : Unable to process a controller whose SampleRateHz is 0 now.
11-26 17:49:30.454 32491 32517 I Unity   : Hand tracking: ON
11-26 17:49:30.928 32491 32517 I Unity   : [OVRManager] HMDUnmounted event
11-26 17:49:30.939 32491 32517 I Unity   : AVProVideoPlayer Event: Paused
11-26 17:49:31.123 32491 32517 I Unity   : [OVRManager] HMDMounted event
11-26 17:49:31.135 32491 32517 I Unity   : AVProVideoPlayer Event: Unpaused
11-26 17:49:31.400 32491 32517 I Unity   : Recenter event detected
11-26 17:49:31.433 32491 32517 I Unity   : Recenter event detected
11-26 17:49:35.447 32491 32517 I Unity   : Recenter event detected
11-26 17:51:00.838 32491 32517 I Unity   : ActionController_ChangeDevice QuestHandTrackingController Left
11-26 17:51:00.838 32491 32517 I Unity   : ActivateLeftController
11-26 17:51:00.881 32491 32517 I Unity   : ActionController_ChangeDevice QuestHandTrackingController Right
11-26 17:51:00.881 32491 32517 I Unity   : ActivateRightController
11-26 17:51:02.458 32491 32517 I Unity   : Hand tracking: OFF
11-26 17:51:02.515 32491 32517 I Unity   : ActionController_ChangeDevice RiftController Right
11-26 17:51:02.515 32491 32517 I Unity   : ActivateRightController
11-26 17:51:05.157 32491 32517 I Unity   : activeDecodeThreadCount 0 decodedFrameCount 0 droppedFrameCount 0
11-26 17:51:05.158 32491 32517 I Unity   : AVProVideoPlayer Event: Closing
11-26 17:51:05.175 32491 32517 I Unity   : [HapticStreamService].Disconnect   
11-26 17:51:05.178 32491 32517 W Unity   : [CmstAnalytics] CamEnterExitEvent, missing videodata for event:Cmst cam exited
11-26 17:51:05.178 32491 32517 W Unity   : Analytics.CmstAnalytics:OnCamExited()
11-26 17:51:05.178 32491 32517 W Unity   : PlayerController:OnDisable()
11-26 17:51:05.178 32491 32517 W Unity   : UnityEngine.Events.UnityEvent:Invoke()
11-26 17:51:05.178 32491 32517 W Unity   : CustomButton:Execute(CustomButtonEventType)
11-26 17:51:05.178 32491 32517 W Unity   : UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
11-26 17:51:05.178 32491 32517 W Unity   : UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessPointerButton(ButtonDeltaState, PointerEventData)
11-26 17:51:05.178 32491 32517 W Unity   : UnityEngine.XR.Interaction.Toolkit.UI.UIInputModule:ProcessTrackedDevice(TrackedDeviceModel&, Boolean)
11-26 17:51:05.178 32491 32517 W Unity   : UnityEngine.XR.Interaction.Toolkit.UI.XRUIInputModule:DoProcess()
11-26 17:51:05.178 32491 32517 W Unity   : 
11-26 17:51:05.224 32491 32517 I Unity   : Reloading dashboard: ReloadMedia
11-26 17:51:07.129 32491 32517 I Unity   : [ApplicationExit] Started to execute the exit handlers..
11-26 17:51:07.131 32491 32517 I Unity   : [CommandsSender] StopAsync: Loop already stopped.
11-26 17:51:07.132 32491 32517 I Unity   : [CommandsSender] StopAsync: Loop already stopped.
11-26 17:51:07.134 32491 32517 I Unity   : [AutoBlowDeviceController] Stopping loop from ApplicationExit_ExitHandler.
11-26 17:51:07.135 32491 32517 I Unity   : [AutoBlowDeviceController] StopAsync: Loop already stopped.
11-26 17:51:07.135 32491 32517 I Unity   : [HandyDeviceController] Stopping loop from ApplicationExit_ExitHandler.
11-26 17:51:07.135 32491 32517 I Unity   : [HandyDeviceController] StopAsync: Loop already stopped.
11-26 17:51:07.152 32491 32517 I Unity   : [ApplicationExit] OnApplication_WantsToQuit   
11-26 17:51:07.154 32491 32517 I Unity   : [AVProVideo] Shutdown
11-26 17:51:07.170 32491 32517 I Unity   : [OVRManager] OnApplicationQuit
11-26 17:51:07.175 32491 32517 I Unity   : Disconnecting NS...
11-26 17:51:07.225 32491 32517 I Unity   : [OVRManager] OnDestroy
```

**Comment by Ste-RH** [comment]
'GetDecoderPerformance' is a Windows platform only feature

**Comment by Tormund** [comment]
@Ste-RH Are we able to retrieve stats on Android? In particular, I am interested in dropped frames.

**Comment by Ste-RH** [comment]
No, not currently.  We do not have any plans to investigate this either.  If you want to open an enhancement request then we can add it to the list...but this is unlikely to be high priority as you are the only person to ever ask for it!
