### ISSUE TITLE
Exoplayer loading failed at random

### ISSUE THREAD

**Issue by MatzeOGH** [RenderHeads/UnityPlugin-AVProVideo#36]
**Describe the bug**
I have a bit of a problem with the exoplayer on android.
The Player works perfectly for a while but at some point it randomly stops playing the movie.
This problem persists until I restart the phone. Restarting the app does not solve the problem. 

**Your Setup (please complete the following information):**
 - Unity 2018.2.21f1: 
 - AVPro Video version: v.1.9.12
 - Operating system version: 
 - Device model: Samsung Galaxy S6 SM-G920F
 - Video specs (resolution, frame-rate, codec, file size): 2880x2880 + spatial audio with facebook audio 360

**To Reproduce**
1. Left the phone in standby over a couple of hours without playing anything
2. tried to play the same movie clip it already played hundreds of times before

**Logs**
`AndroidPlayer(samsung_SM-G920F@192.168.1.3)</i> [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.`
```
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal: Playback error.
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:450)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at android.os.Handler.dispatchMessage(Handler.java:98)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at android.os.Looper.loop(Looper.java:154)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at android.os.HandlerThread.run(HandlerThread.java:61)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [2880, 2880, -1.0], [-1, -1])
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         ... 9 more
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal: Caused by: java.lang.IllegalArgumentException
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at android.media.MediaCodec.native_configure(Native Method)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at android.media.MediaCodec.configure(MediaCodec.java:1882)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:453)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:427)
03-31 21:20:11.526  5827  6767 E ExoPlayerImplInternal:         ... 8 more

```

**Comment by MatzeOGH** [comment]
2019-04-01 20:47:41.720 32509-551/? E/BufferQueueProducer: [SurfaceTexture-36-32509-0] connect: already connected (cur=3 req=3)
2019-04-01 20:47:41.721 32509-551/? E/MediaCodec: native_window_api_connect returned an error: Invalid argument (-22)
2019-04-01 20:47:41.721 32509-32657/? E/MediaCodec: configure failed with err 0xffffffea, resetting...
2019-04-01 20:47:41.753 32509-32657/? E/ExoPlayerImplInternal: Playback error.
    com.google.android.exoplayer2.ExoPlaybackException
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:450)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, video/avc, -1, null, [2880, 2880, -1.0], [-1, -1])
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:437) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
     Caused by: java.lang.IllegalArgumentException
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1882)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:453)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:427)
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:929) 
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:506) 
        at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:566) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:518) 
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:301) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.os.HandlerThread.run(HandlerThread.java:61) 
2019-04-01 20:47:41.771 32509-32524/? E/Unity: [AVProVideo] Error: Loading failed.  File not found, codec not supported, video resolution too high or insufficient system resources.

**Comment by MatzeOGH** [comment]
anyone home?

**Comment by MatzeOGH** [comment]
I had the phone in standby for a day and the error occurred again.
There were no apps running only default android.

The exception only disappeared after restarting the phone.

**Comment by AndrewRH** [comment]
Thanks for reporting this, and for these great reproduction details.
We will look into it and get back to you.

**Comment by AndrewRH** [comment]
From email thead [#2q6QC]

**Comment by AndrewRH** [comment]
We've just released a new version of AVPro Video (v.1.9.17) which should fix this issue.  Please do test it and let us know if if this resolves it for you.

Thanks,

**Comment by AndrewRH** [comment]
We'll close this issue in a couple of days, as we've proposed a solution (new plugin version) but haven't heard anything back.  

Thanks,

**Comment by AndrewRH** [comment]
Closing this issue - presumed fixed
