### ISSUE TITLE
Minify with Proguard: java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo 

### ISSUE THREAD

**Issue by RemyRM** [RenderHeads/UnityPlugin-AVProVideo#455]
**Describe the bug**
When building a project while having the options for minify (Project Settings > Player > Publishing Settings > Minify) on Android set to Proguard on both Release and Debug the build fails with an exception: `java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo `

**Your Setup (please complete the following information):**
 - Unity version: 2019.3.13f1
 - AVPro Video version: 1.11.4
 - Operating system version: Windows pro 64 bit
 - Device model: Samsung galaxy S8/S6 (ARM64)
 - Video specs (resolution, frame-rate, codec, file size): standard AVProVideoSamples/SampleCube.mp4 video

**To Reproduce**
1. Create a new project
2. Install the AVPro video package and open up a (360) demo scene
3.  set the minify options to proguard (Project Settings > Player > Publishing Settings > Minify) 
4. Build the project
5. Building the project with "Minify" set to "None" yields a working build.

**Logs**
> AndroidPlayer(ADB@127.0.0.1:34999) AndroidJavaException: java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo
java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:83)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:214)
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.RenderHeads.AVProVideo.AVProMobileVideo" on path: DexPathList[[zip file "/data/app/com.FBTest.FirebaseTest-ZYCnnHdcU8bt9avzQCqqCg==/base.apk"],nativeLibraryDirectories=[/data/app/com.FBTest.FirebaseTest-ZYCnnHdcU8bt9avzQCqqCg==/lib/arm, /data/app/com.FBTest.FirebaseTest-ZYCnnHdcU8bt9avzQCqqCg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 8 more
  at UnityEngine.AndroidJNISafe.CheckException () [0x0008d] in /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJNISafe.cs:24 
  at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x0000c] in /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJNISafe.cs:107 
  at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args) [0x00023] in /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:351 
  at UnityEngine.AndroidJavaObject..ctor (System.String className, System.Object[] args) [0x00008] in /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJava.cs:217 
  at RenderHeads.Media.AVProVideo.AndroidMediaPlayer.InitialisePlatform () [0x00065] in C:\Dev\Unity\FirebaseTest\Assets\AVProVideo\Scripts\Internal\AndroidMediaPlayer.cs:97 
  at RenderHeads.Media.AVProVideo.MediaPlayer.CreatePlatformMediaPlayer () [0x00003] in C:\Dev\Unity\FirebaseTest\Assets\AVProVideo\Scripts\Components\MediaPlayer.cs:1947 
  at RenderHeads.Media.AVProVideo.MediaPlayer.Initialise () [0x00001] in C:\Dev\Unity\FirebaseTest\Assets\AVProVideo\Scripts\Components\MediaPlayer.cs:775 
  at RenderHeads.Media.AVProVideo.MediaPlayer.Start () [0x0000f] in C:\Dev\Unity\FirebaseTest\Assets\AVProVideo\Scripts\Components\MediaPlayer.cs:821 
 
(Filename: /Users/builduser/buildslave/unity/build/Modules/AndroidJNI/AndroidJNISafe.cs Line: 24)

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by AndrewRH** [comment]
Hi,

Are you doing an ARM64 build?  If so, the plugin files may need to be set correctly in the inspector as mentioned here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/112

Or is it working correctly with minify disabled?

Thanks,

**Comment by RemyRM** [comment]
hi @AndrewRH ,

Yes this is using ARM64, and works with minify disabled.

It indeed seems like I had to re-set the arm64 flags. Could it be those get reset when updating to a newer version? (Might be i'm confusing having set those flags in a different project though)

**Comment by RemyRM** [comment]
@AndrewRH 

Thank you for your quick reply.

Yes this is an ARM64 Build, the flags as explained in the #112 issue were indeed unset. After setting those as explained there the issue remains. Setting the minify options to none yields a working build.

**Comment by RenderHeadsSte** [comment]
I know what is happening here, but not entirely sure why.

I think the 'minify' setting via proguard is obfuscating the java code.  This is leading to class access from the c# script code in AVPro Video not being able to find the correct class.

The part I am not sure about is how the compiled AVPro Video plugin code is then being obfuscated further by the unity build pipeline.

I think the bottom line here is that you cannot use the minify setting.

**Comment by ZimM-LostPolygon** [comment]
The problem is that sometimes it is not even possible to NOT use minification. We are using many Java libraries in a project, and it easily breaks through the 64k DEX method limit. In other words, the game won't even build unless minification is enabled. But it seems like AVProVideo doesn't have a ProGuard configuration file that would protect against classes being minified. So what's the solution here?
