### ISSUE TITLE
Video wont play when built and run on Android device

### ISSUE THREAD

**Issue by nsmith1024** [RenderHeads/UnityPlugin-AVProVideo#465]
**Describe the bug**

Build for Android device, videos wont play

**Your Setup (please complete the following information):**
 - Unity version: 2020.1.2
 - AVPro Video version: unknown
 - Operating system version: Android
 - Device model: 
 - Video specs (resolution, frame-rate, codec, file size): 

**To Reproduce**
1. Build for target Android
2. 
3. 

**Logs**
If applicable, add error logs to help explain your problem.

2020-09-14 16:51:42.738 8920-8960/com.myApp.myApp E/Unity: AndroidJavaException: java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo
    java.lang.ClassNotFoundException: com.RenderHeads.AVProVideo.AVProMobileVideo
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:237)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.RenderHeads.AVProVideo.AVProMobileVideo" on path: DexPathList[[zip file "/data/app/com.myApp.myApp-E1ofahm_UZkUBdJJacwCgg==/base.apk"],nativeLibraryDirectories=[/data/app/com.myApp.myApp-E1ofahm_UZkUBdJJacwCgg==/lib/arm64, /data/app/com.myApp.myApp-E1ofahm_UZkUBdJJacwCgg==/base.apk!/lib/arm64-v8a, /system/lib64]

**Comment by nsmith1024** [comment]
Seems if i uncheck "debug build" in the Build Settings, it stops working. Im using the demo version of your player. So the demo version of your player  only works with a debug build?

**Comment by AndrewRH** [comment]
Hi this is probably caused by making an ARM64 build.  You can fix this by one of 2 ways:

1) Go to Player Settings and changing the build architecture to remove ARM64
2) Go to /Plugins/Android/libs/arm64-v8a  and select each file and assign the correct CPU architecture.  You can find reference to that here:
https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/112#issuecomment-509605543

I hope that helps solve the problem.

Thanks,

**Comment by nsmith1024** [comment]
problem has been fixed
