### ISSUE TITLE
Once a bug comes out with Pico and AVPro

### ISSUE THREAD

**Issue by varunitestudio** [RenderHeads/UnityPlugin-AVProVideo#576]
Pico Stopping Phenomenon due to Fatal Error

I play 360 3D video using pico 4K G2 and AVPro.

But when you start the app, the app stops with the error below.

Android Studio says as follows.

2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #01 pc 00095229 /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR::TimeWarpLocal::WarpSwapInternal(pvrTimeWarpParms const&)+508) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #02 pc 0009544f /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR::TimeWarpLocal::WarpSwap(pvrTimeWarpParms const&)+46) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #03 pc 0004e2b1 /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR_TimeWarpEvent_+988) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #04 pc 0005146f /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (OnRenderEvent_+446) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #05 pc 0064ad4c /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #06 pc 00255385 /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #07 pc 00256463 /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #08 pc 0024f2ef /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
2021-01-16 15:53:57.833 26764-26865/? E/CRASH: #09 pc 003ad10f /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
2021-01-16 15:53:59.176 2222-3162/? V/UnityPlayerActivity: startBroadCast(). while
2021-01-16 15:54:02.859 26764-26764/? E/MessageQueue-JNI: java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.12f1 (225e826a680e)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a'
Build fingerprint: 'Pico/A7910_KT/PICOA7910:8.1.0/OPM1.171019.026/eng.scmbui.20200924.223445:user/test-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2021-01-16 15:53:57+0900
pid: 26764, tid: 26865, name: Thread-37 >>> com.VariousStudio.StudioVANDALEnding <<<
uid: 10074
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
r0 00000000 r1 000068f1 r2 00000006 r3 00000008
r4 0000688c r5 000068f1 r6 ce076904 r7 0000010c
r8 00000000 r9 d7895ec0 r10 00000088 r11 00000000
ip a26069e8 sp ce0768f0 lr f356a7a7 pc f3564764

backtrace:
      #00 pc 0001a764  /system/lib/libc.so (abort+64) (BuildId: 7e441ac735842f5185c797f24487fa42)
      #01 pc 00095229  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR::TimeWarpLocal::WarpSwapInternal(pvrTimeWarpParms const&)+508) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #02 pc 0009544f  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR::TimeWarpLocal::WarpSwap(pvrTimeWarpParms const&)+46) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #03 pc 0004e2b1  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR_TimeWarpEvent_+988) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #04 pc 0005146f  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (OnRenderEvent_+446) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #05 pc 0064ad4c  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #06 pc 00255385  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #07 pc 00256463  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #08 pc 0024f2ef  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #09 pc 003ad10f  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #10 pc 0004726f  /system/lib/libc.so (__pthread_start(void*)+22) (BuildId: 7e441ac735842f5185c797f24487fa42)
      #11 pc 0001b229  /system/lib/libc.so (__start_thread+32) (BuildId: 7e441ac735842f5185c797f24487fa42)

    at libc.abort(abort:64)
    at libPvr_UnitySDK.PVR::TimeWarpLocal::WarpSwapInternal(pvrTimeWarpParms const&)(WarpSwapInternal:508)
    at libPvr_UnitySDK.PVR::TimeWarpLocal::WarpSwap(pvrTimeWarpParms const&)(WarpSwap:46)
    at libPvr_UnitySDK.PVR_TimeWarpEvent_(PVR_TimeWarpEvent_:988)
    at libPvr_UnitySDK.OnRenderEvent_(OnRenderEvent_:446)
    at libunity.0x64ad4c(Native Method)
    at libunity.0x255385(Native Method)
    at libunity.0x256463(Native Method)
    at libunity.0x24f2ef(Native Method)
    at libunity.0x3ad10f(Native Method)
    at libc.__pthread_start(void*)(__pthread_start:22)
    at libc.__start_thread(__start_thread:32)
2021-01-16 15:54:02.861 26764-26764/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.VariousStudio.StudioVANDALEnding, PID: 26764
java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Version '2019.4.12f1 (225e826a680e)', Build type 'Release', Scripting Backend 'mono', CPU 'armeabi-v7a'
Build fingerprint: 'Pico/A7910_KT/PICOA7910:8.1.0/OPM1.171019.026/eng.scmbui.20200924.223445:user/test-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2021-01-16 15:53:57+0900
pid: 26764, tid: 26865, name: Thread-37 >>> com.VariousStudio.StudioVANDALEnding <<<
uid: 10074
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
r0 00000000 r1 000068f1 r2 00000006 r3 00000008
r4 0000688c r5 000068f1 r6 ce076904 r7 0000010c
r8 00000000 r9 d7895ec0 r10 00000088 r11 00000000
ip a26069e8 sp ce0768f0 lr f356a7a7 pc f3564764

backtrace:
      #00 pc 0001a764  /system/lib/libc.so (abort+64) (BuildId: 7e441ac735842f5185c797f24487fa42)
      #01 pc 00095229  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR::TimeWarpLocal::WarpSwapInternal(pvrTimeWarpParms const&)+508) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #02 pc 0009544f  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR::TimeWarpLocal::WarpSwap(pvrTimeWarpParms const&)+46) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #03 pc 0004e2b1  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (PVR_TimeWarpEvent_+988) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #04 pc 0005146f  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libPvr_UnitySDK.so (OnRenderEvent_+446) (BuildId: 85126c98609bb95ee5472d838b72cb6d2e3c8fd2)
      #05 pc 0064ad4c  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #06 pc 00255385  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #07 pc 00256463  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #08 pc 0024f2ef  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #09 pc 003ad10f  /data/app/com.VariousStudio.StudioVANDALEnding-tED4_VchtkPNUJvqU-DbxQ==/lib/arm/libunity.so (BuildId: bd5d7e2044c82b2cdcdd04860214fb642c0d3589)
      #10 pc 0004726f  /system/lib/libc.so (__pthread_start(void*)+22) (BuildId: 7e441ac735842f5185c797f24487fa42)
      #11 pc 0001b229  /system/lib/libc.so (__start_thread+32) (BuildId: 7e441ac735842f5185c797f24487fa42)

    at libc.abort(abort:64)
    at libPvr_UnitySDK.PVR::TimeWarpLocal::WarpSwapInternal(pvrTimeWarpParms const&)(WarpSwapInternal:508)
    at libPvr_UnitySDK.PVR::TimeWarpLocal::WarpSwap(pvrTimeWarpParms const&)(WarpSwap:46)
    at libPvr_UnitySDK.PVR_TimeWarpEvent_(PVR_TimeWarpEvent_:988)
    at libPvr_UnitySDK.OnRenderEvent_(OnRenderEvent_:446)
    at libunity.0x64ad4c(Native Method)
    at libunity.0x255385(Native Method)
    at libunity.0x256463(Native Method)
    at libunity.0x24f2ef(Native Method)
    at libunity.0x3ad10f(Native Method)
    at libc.__pthread_start(void*)(__pthread_start:22)
    at libc.__start_thread(__start_thread:32)

What's the problem?

**Your Setup (please complete the following information):**
 - Unity version: Unity3D 2019.4.12f
 - AVPro Video version: AVPro v2.0.1
 - Operating system version: 
 - Device model: Pico 2G 4K
 - Video specs (resolution, frame-rate, codec, file size):

**Comment by RenderHeadsSte** [comment]
Nothing in your logs appears to mention AVPro Video.  Is this running one of our demo scenes?  Have you tried setting up a scene without AVPro Video to make sure it is the introduction of AVPro Video that is causing this issue?

**Comment by varunitestudio** [comment]
I also asked Pico about the compatibility between Pico SDK and AVPro SDK. So I asked if it was a question that I knew.

Pico is also trying to find the cause.

This is a link to the Pico question.
https://github.com/picoxr/support/issues/47

**Comment by RenderHeadsSte** [comment]
Oki, so Pico SDK does not support single pass?  Shame, as it is more optimal.

We do have a fix in the pipeline for multi pass stereo rendering.  If you send an email to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) then we can get it over to you for pre-release testing if you are interested.

**Comment by RenderHeadsSte** [comment]
@varunitestudio The newly release v2.0.2 has a component (UpdateMultipassStereo) that should allow multipass stereo support now.  Please do update and let us know if it fixes your stereo issue.

**Comment by varunitestudio** [comment]
How should I test it?

Can I uncheck Use Single Pass and see if it comes out in 3D?

**Comment by varunitestudio** [comment]
It was tested on Pico using AVPro v2.0.2.

The Use Single Pass was unchecked and 3D images were checked.

It seems necessary to test whether there is a continuous problem.

**Comment by RenderHeadsSte** [comment]
> It was tested on Pico using AVPro v2.0.2.
> 
> The Use Single Pass was unchecked and 3D images were checked.
> 
> It seems necessary to test whether there is a continuous problem.

Did you test with the 'UpdateMultipassStereo' component added?

**Comment by RenderHeadsSte** [comment]
We will be closing this issue soon due to lack of response
