### ISSUE TITLE
Fatal Exception ExoPlayer

### ISSUE THREAD

**Issue by JanOwiesniak** [RenderHeads/UnityPlugin-AVProVideo#623]
**Setup**
 - Unity version: 2019.4.18f1
 - AVPro Video version: v2.0.6 Ultra Edition
 - Operating system version: macOS Catalina 10.15.6 (19G2021)
 - Device model: Android Studio: MacBook Pro (2016); App: Nokia 6.1

**Bug**

Exported Unity via Player Settings to Android Studio. Run in `debug` mode - everything is fine. Run in `release` mode - app crashes with following error message:

**Logs**

```
    --------- beginning of crash
2021-02-10 12:52:49.385 4549-4645/? E/AndroidRuntime: FATAL EXCEPTION: ExoPlayer:Playback
    Process: app.baff, PID: 4549
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplr2avp.extractor.TrackOutput.sampleData(com.google.android.exoplr2avp.util.ParsableByteArray, int)"
        at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:536)
        at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:200)
        at com.google.android.exoplr2avp.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplr2avp.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-02-10 12:52:49.385 4549-4649/? E/AndroidRuntime: FATAL EXCEPTION: Loader:ProgressiveMediaPeriod
    Process: app.baff, PID: 4549
    java.lang.AbstractMethodError: abstract method "void com.google.android.exoplr2avp.extractor.TrackOutput.sampleData(com.google.android.exoplr2avp.util.ParsableByteArray, int)"
        at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:536)
        at com.google.android.exoplr2avp.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:200)
        at com.google.android.exoplr2avp.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplr2avp.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1046)
        at com.google.android.exoplr2avp.upstream.Loader$LoadTask.run(Loader.java:415)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2021-02-10 12:52:49.914 4276-6370/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2021-02-10 12:52:49.914 4276-6370/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2021-02-10 12:52:49.917 4276-6370/? E/SDHMS:SDHMS_UTIL_IO: e = /sys/class/input_booster/touchkey/time (Permission denied)
2021-02-10 12:52:49.939 26391-26473/? E/PBSessionCacheImpl: sessionId[116070458424781623] not persisted.
2021-02-10 12:52:50.036 2838-2862/? E/Layer: $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
2021-02-10 12:52:50.036 2838-2862/? E/Layer: Abnormal Layer [Screenshot Parent]
2021-02-10 12:52:50.048 2836-2955/? E/NativeSemDvfsCpuManager: release:: Start
2021-02-10 12:52:50.048 2836-2955/? E/NativeSemDvfsCpuManager: release():: mIsAcquired = 1 , mName = CPU  , mTagName : AudioFlinger 
2021-02-10 12:52:50.049 2836-2955/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseDVFSLock() 
2021-02-10 12:52:50.049 2836-2955/? E/NativeSemDvfsCpuManager: release:: End
2021-02-10 12:52:50.057 2838-2862/? E/Layer: $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
2021-02-10 12:52:50.057 2838-2862/? E/Layer: Abnormal Layer [Screenshot Parent]
2021-02-10 12:52:50.449 3253-3501/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2021-02-10 12:52:55.085 3253-3612/? E/Watchdog: !@Sync 748 [2021-02-10 12:52:55.085] FD count : 507
```

**Comment by RenderHeadsSte** [comment]
I believe the fix for this is outlined [here](https://github.com/RenderHeads/UnityPlugin-AVProVideo/issues/580#issuecomment-763828601) in issue #580

**Comment by RenderHeadsSte** [comment]
Can you confirm this fixes the issue @JanOwiesniak ?

**Comment by JanOwiesniak** [comment]
Upgraded from 1.x to 2.x previous and some Android Plugins were duplicate in Assets folder. Removed it, cleaned and rebuild Android project. Error is gone.

**Comment by jyotisingla8611** [comment]
Add this line in proguard config file fixes the issue for me.
`-keepnames class com.google.common.** { *; }`

https://github.com/google/ExoPlayer/issues/8128#issuecomment-728765083
