### ISSUE TITLE
The android app is crashing (abstract method "void com.google.android.exoplr2avp.Player$EventListener.onEvents)

### ISSUE THREAD

**Issue by KolesnikovProduction** [RenderHeads/UnityPlugin-AVProVideo#859]
**Describe the issue**
When launching the application, the following error occurs and the application crashes. The error does not appear on every device. Works on OnePlus 7T Pro.

**Your Setup (please complete the following information):**
 - Unity version: 2019.4.26.1
 - AVPro Video version: 2.1.5
 - Operating system version: Android
 - Device model: huawei p20 PRO

**Logs**
abstract method "void com.google.android.exoplr2avp.Player$EventListener.onEvents(com.google.android.exoplr2avp.Player, com.google.android.exoplr2avp.Player$Events)" : java.lang.AbstractMethodError: abstract method "void com.google.android.exoplr2avp.Player$EventListener.onEvents(com.google.android.exoplr2avp.Player, com.google.android.exoplr2avp.Player$Events)"
        at com.google.android.exoplr2avp.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:181)
        at com.google.android.exoplr2avp.-$$Lambda$ExoPlayerImpl$lF8tBLwdfQWPzmCKmB9JOL_MMMU.invoke(Unknown Source:4)
        at com.google.android.exoplr2avp.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:294)
        at com.google.android.exoplr2avp.util.ListenerSet.handleMessage(ListenerSet.java:239)
        at com.google.android.exoplr2avp.util.ListenerSet.lambda$6tgPaBHXWbdeZOcwgCMHdP8SLjk(Unknown Source:0)
        at com.google.android.exoplr2avp.util.-$$Lambda$ListenerSet$6tgPaBHXWbdeZOcwgCMHdP8SLjk.handleMessage(Unknown Source:2)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:166)
        at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

**Comment by RenderHeadsSte** [comment]
Possibly linked to #580 ?  Can you try the fixes offered in that thread?  Also ensure you do not have minify enabled.

**Comment by KolesnikovProduction** [comment]
> Possibly linked to #580 ? Can you try the fixes offered in that thread? Also ensure you do not have minify enabled.

This is the first thing I tried.

The first recommendation is to add a line to the Properties Template **android.enableDexingArtifactTransform=false**.
The second recommendation does not make sense, since I do not use **proguard**.

In unity 2019.4.0 everything worked well. After upgrading to version 2019.4.26 errors have appeared.

**Comment by kahnivore** [comment]
Have you tried upgrading to the LTS version, 2019.4.28?

**Comment by RenderHeadsSte** [comment]
Can you send over your project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) so we can diagnose?

**Comment by KolesnikovProduction** [comment]
> Have you tried upgrading to the LTS version, 2019.4.28?
Will it help?
We recently committed to version 2019.4.26.1. This requires the allocation of certain resources to update unity for the entire team.

**Comment by KolesnikovProduction** [comment]
> Can you send over your project to [unitysupport@renderheads.com](mailto:unitysupport@renderheads.com) so we can diagnose? Please mark the subject line #859

I will not be able to send the project itself, but I will try to reproduce a demo project with a problem.
