### ISSUE TITLE
Minify support 

### ISSUE THREAD

**Issue by tylkomat** [RenderHeads/UnityPlugin-AVProVideo#944]
**Describe the issue**
The com.renderheads.AVPro.Video.Manager is not found when building for production. It works properly when having `Development Build` checked in Build Settings.

**Your Setup (please complete the following information):**
 - Unity version: v2019.4.3f1 WindowsEditor
 - AVPro Video version: v2.2.1 (plugin v2.2.0f1-core)
 - Operating system version: Desktop - HP ProBook 450 G5 (HP) - Windows 10  (10.0.0) 64bit - German
 - Device model: Nokia 7.2, Android 10
 - Video specs (resolution, frame-rate, codec, file size): 
   https://www.b-tu.de/streaming/vimp//smil:0cd1bfd44468bab9b01e27e6a1e749dd_1587384325.smil/playlist.m3u8

**To Reproduce**
1. Start an empty project
2. Import AVPro package
3. select Demo_MediaPlayer as default scene
3. Build with production settings

**Logs**
```
AndroidJavaException: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager: com.DefaultCompany.avprotest2
java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager: com.DefaultCompany.avprotest2
	at java.lang.Class.classForName(Native Method): com.DefaultCompany.avprotest2
	at java.lang.Class.forName(Class.java:454): com.DefaultCompany.avprotest2
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method): com.DefaultCompany.avprotest2
	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0): com.DefaultCompany.avprotest2
	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:83): com.DefaultCompany.avprotest2
	at android.os.Handler.dispatchMessage(Handler.java:103): com.DefaultCompany.avprotest2
	at android.os.Looper.loop(Looper.java:214): com.DefaultCompany.avprotest2
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20): com.DefaultCompany.avprotest2
Caused by: java.lang.ClassNotFoundException: com.renderheads.AVPro.Video.Manager: com.DefaultCompany.avprotest2
	... 8 more: com.DefaultCompany.avprotest2
  at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 : com.DefaultCompany.avprotest2
  at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <00000000000000000000000000000000>:0 : com.DefaultCompany.avprotest2
  at UnityEngine.AndroidJavaObject._AndroidJavaObject (System.String className, System.Object[] args): com.DefaultCompany.avprotest2
```

**Screenshots**

**Videos**
   https://www.b-tu.de/streaming/vimp//smil:0cd1bfd44468bab9b01e27e6a1e749dd_1587384325.smil/playlist.m3u8

### Please DO NOT LINK / ATTACH YOUR PROJECT FILES HERE
Instead email the link to us unitysupport@renderheads.com

**Comment by RenderHeadsSte** [comment]
Looks like the AVPro Video plugin has not loaded.  Can you post a full logcat please?

**Comment by tylkomat** [comment]
only for the App? [avvideo.log](https://github.com/RenderHeads/UnityPlugin-AVProVideo/files/7251819/avvideo.log)

**Comment by tylkomat** [comment]
Do you need anything else?

**Comment by kahnivore** [comment]
Could you send a copy of your project to unitysupport@renderheads.com? Please include "#944" in the subject line. 

It would be good to be able to see the settings you're using and test it on one of our devices. 

Thanks.

**Comment by kahnivore** [comment]
Thanks for sending the project. 

Seems like it's caused by Minify - if I set that to 'None' it solves the issue. 

Unfortunately Minify is not something we currently support, but we might add support for it at some point in the future.

**Comment by kahnivore** [comment]
@tylkomat found a fix by adding the following:

- Set 'Minify' Release to 'Proguard' in Player Settings -> Publishing Settings -> Minify
- Tick 'Custom Proguard File' just above in Player Settings-> Publishing Settings -> Build
- Add
`-keep class com.renderheads.AVPro.Video.** { *; }
-keep class com.google.android.exoplr2avp.** { *; }
-keep class com.twobigears.audio360.** { *; }`
to the generated proguard-user file 

Could you please test and see if this solves your issue?

**Comment by tylkomat** [comment]
@kahnivore Yes. Awesome!! That works. I tried many settings before, but proguard was the only one I didn't touch. Thanks.

**Comment by GabrielRosenberg** [comment]
I can't get it to work with R8, should the same fix apply or is there something else I can try?

**Comment by Chris-RH** [comment]
What error message are you getting?
